### PR TITLE
Clarity for router defining doc.

### PR DESCRIPTION
**Pull request by anthonyshew**
## 🎯 Changes

Just some more clarity stuff!

Can someone help me out on the protected procedure on line 55? I've never initialized my router like this (but definitely will now, pretty smart) so would be interested to know how you folks do it.

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/next/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
> Can someone help me out on the protected procedure on line 55? I've never initialized my router like this (but definitely will now, pretty smart) so would be interested to know how you folks do it.

What do you mean? Having a procedure straight on the root router, instead of nested on a child? What else is different here?

CleanShot 2022-11-19 at 16 06 23@2x

**Comment by anthonyshew** [comment]
I just wasn't sure if that was the @KATT Approved: Idiomatic tRPC Way :tm:. I know I've heard him describe it but I don't know exactly how it looks when done "best." 🙃

**Review by KATT — APPROVED** [review]

**Review by KATT — CHANGES_REQUESTED** [review]
Will fix, sec

**Review by KATT — COMMENTED** [review]
I just removed the line

cc @anthonyshew a better example on how to do an authed proc can be found here: https://trpc.io/docs/authorization#option-2-authorize-using-middleware

**Review by KATT — APPROVED** [review]

**Pull request merged**
