### PR TITLE
fix transformer types

### PR DESCRIPTION
**Pull request by OrJDev**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/next/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by OrJDev** [comment]
Some tests failed as you see but i think i figured it out

## Solution

Instead of making the baseType reject promises we create a new optional function that will reject promises,
so you can still use transformers like:

### No Error

```ts
{
  transformer: superjson;
}
```

### No Error

```ts
{
  transformer: withTransformer(superjson);
}
```

### Error

```ts
{
  transformer: withTransformer({
    serialize: (data) => {
      // not async so its fine
    },
    deserialize: async (data) => {
      /// cannot be async so error is thrown
    },
  });
}
```

Screenshot_1

**Comment by OrJDev** [comment]
works for react, gotta fix for next

### This will return never so it cannot be used as a valid client
```ts
  const _example = trpc.createClient({
    links: [],
    transformer: {
      serialize: async () => {
        return {};
      },
      deserialize: () => {
        return {};
      },
    },
  });
```
### This is fine and will return a valid trpc client, can be used as a client
```ts
  const _example = trpc.createClient({
    links: [],
    transformer: {
      serialize: () => {
        return {};
      },
      deserialize: () => {
        return {};
      },
    },
  });
```

**Review by KATT — COMMENTED** [review]
I'm starting to feel that the juice might not be worth the squeeze here?

**Comment by OrJDev** [comment]
It is more complicated than it should've been, but after 13 commits I rather just fix it for `next` than throw it away

**Comment by OrJDev** [comment]
Will reopen when i have time

**Pull request closed without merging**
