### PR TITLE
docs(server/routers): add warning to use relative imports to trpc.ts

### PR DESCRIPTION
**Pull request by oleasteo**
## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by Nick-Lucas** [comment]
This really depends on your setup, typescript can absolutely bring in tRPC types by absolute import, so if you've had this experience there was likely a problem with your setup

Feel free to to come to our discord as someone may be able to help there

**Comment by oleasteo** [comment]
@Nick-Lucas I've added an example with npm-workspaces, see #6114 

In there, you can reproduce the issue by replacing `from './trpc.js'` with `from '@/trpc.js'` in *server/user.router.ts*. This will result in `trpc.user: any` in the client.

So, if you don't happen to know a fix, we should definitely add such a warning (with the added context of npm workspaces) to the docs.

**Comment by Nick-Lucas** [comment]
> @Nick-Lucas I've added an example with npm-workspaces, see #6114
> 
> In there, you can reproduce the issue by replacing `from './trpc.js'` with `from '@/trpc.js'` in _server/user.router.ts_. This will result in `trpc.user: any` in the client.
> 
> So, if you don't happen to know a fix, we should definitely add such a warning (with the added context of npm workspaces) to the docs.

It really is a typescript setup issue in the project, I pointed out one possible thing though I know you're also referring to a different file in this comment.

Absolute imports require proper configuration in both tsconfig and build tools. It's fiddly but there's no justification for this comment being added to the docs because it's at very least misleading. Some documentation on how to correctly set up typescript for various repo types would be far more helpful

**Comment by oleasteo** [comment]
I don't accept "setup issue" until one shows me, how, exactly. As far as I'm concerned, this is reproducible simply once client and server ain't in the same package, with pretty straight-forward setup. Nothing complicated. Common use-case.

I've dug into the issues and found two other related ones: #3475 and #2928. Both, closed without any addressing the issue.
So, sorry if I have to insist on some kind of solution here ;-)

**Comment by KATT** [comment]
@oleasteo 

- https://github.com/trpc/examples-next-prisma-starter/blob/97c3dfbf7d7902bc8394756a58ef916e7eda6d82/tsconfig.json#L22. 
- https://github.com/trpc/examples-next-prisma-starter/blob/97c3dfbf7d7902bc8394756a58ef916e7eda6d82/src/pages/post/%5Bid%5D.tsx#L7
- https://github.com/trpc/examples-next-prisma-starter/blob/97c3dfbf7d7902bc8394756a58ef916e7eda6d82/src/pages/post/%5Bid%5D.tsx#L35

**Comment by oleasteo** [comment]
@KATT that's the client-side code.

https://github.com/trpc/examples-next-prisma-starter/blob/97c3dfbf7d7902bc8394756a58ef916e7eda6d82/src/server/routers/post.ts#L5
server-side there is a relative import. I'd expect that to cause the same issue if resolved via some path alias.

**Comment by oleasteo** [comment]
Solved. I'll update #6114 shortly to provide a reference solution and will open a PR to update the FAQ/Troubleshooting.

**Pull request closed without merging**
