### PR TITLE
Fixed a bug where there was no fetch implementation found in the minimal example

### PR DESCRIPTION
**Pull request by mattpocock**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by ixahmedxi — APPROVED** [review]

**Comment by kamilogorek** [comment]
What would be the case when it actually happens?
Also as it's client-side code, I'd use https://github.com/github/fetch directly instead.

**Review by KATT — COMMENTED** [review]
@mattpocock are you not using node 18? :)

**Comment by mattpocock** [comment]
@KATT Whoops, no! 16.

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Pull request closed without merging**
