### PR TITLE
[Dev environment] Add support for node 16

### PR DESCRIPTION
**Pull request by Perfect7M**
# Add support for node 16

I'm using node 16 which is the current LTS but the project was not supporting it and I couldn't run install. I saw here https://github.com/trpc/trpc/issues/887#issue-988454508 that the next major version will have node 16 support. Two major questions:

- Should I make this branch against the `next` branch?
- What should I change to fulfill this point?

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
The project supports node 16 in terms of usage, but there was something with the completed build that got messed up with node 16. Forgot what at this point.

Looks like I did it in #1304 😅

**Comment by KATT** [comment]
Try updating all the [workflows](https://github.com/trpc/trpc/tree/main/.github/workflows) to 16 in this PR and see if it still passes.

**Comment by Perfect7M** [comment]
@KATT made some upgrades to node 16 as its current LTS and it seems like everything is passing.

I wonder about the reason behind making `examples-node12.yml` and `examples.yml`. I see there are some discrepancies but could you please elaborate on why they are separate?

**Comment by KATT** [comment]
> I wonder about the reason behind making `examples-node12.yml` and `examples.yml`. I see there are some discrepancies but could you please elaborate on why they are separate?

I don't care about supporting node 12 and I've deleted it in the [next](https://github.com/trpc/trpc/tree/next)-branch so I just have a limited subset there

**Comment by KATT** [comment]
> @KATT made some upgrades to node 16 as its current LTS and it seems like everything is passing.

Maybe it was a temporary glitch 🤔

**Review by KATT — DISMISSED** [review]
Nice!

**Review by KATT — APPROVED** [review]

**Pull request merged**
