### PR TITLE
Start My Journey to translate the Docs to Arabic.

### PR DESCRIPTION
**Pull request by a4addel**
## 🎯 Changes
* Create a copy of the file with `.ar.md` extension to differ it from other languages.
* 
What changes are made in this PR? Is it a feature or a bug fix?
Docs.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/next/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by dyaa** [comment]
I'm Arabic speaker and I'm ready to help reviewing this one
Good luck
حظا سعيد

**Review by KATT — COMMENTED** [review]
I love this.... but I don't see how we as an largely unpaid OSS-team are able to maintain this? 😬 

We've had a similar one for Chinese #2142

**Comment by a4addel** [comment]
> I don't see how we as an largely unpaid OSS-team are able to maintain this? 😬

It will be maintained by people like ,me, Who Don't wanna get paid in the first place.

**Comment by dyaa** [comment]
@a4addel, I believe financing is not the problem here, It's about the long term maintainability of the translations and the actual value those translations would bring to the library users.

My personal opinion here and as a person with the same language, I wouldn't go for Arabic documentation because:
1. The community is English-first
1. Not all technical terms can be translated to Arabic
1. https://github.com/trpc/trpc/pull/2142

**Comment by a4addel** [comment]
> 1. The community is English-first
The community being English-first has nothing to do with a other language has it's own translation of the Docs it's not like, they both can exist at the same time.

> 2. Not all technical terms can be translated to Arabic
In Tech, no one Translates the technical terms they just use the English words in the Middle of the Arabic sentence, like the Medical Terms, they are universal all the doctors around the word knows the Latin word of a diseases Regardless of what there native toung is.

> 3. It's about the long term maintainability of the translations 
Nothing Open Source guarantees a long term maintenance, except if there is Company behind it.

> 4. those translations would bring to the library users.

> 5. those translations would bring to the library users.
 There is people out there that doesn't have enough English skills to read Docs, Yes They can learn it, but wouldn't it be better if they had a Source in there native tongue they can use till they improve their English Skills ?

**Comment by ixahmedxi** [comment]
Hello there, I'm part of the tRPC team and also an Arabic native speaker. We have previously talked about providing translations of the documentation in multiple languages as that the team in itself is very diverse with people knowing multiple languages and we came to the conclusion that of course we would love to provide documentation in different languages, but the fact is tRPC is rapidly evolving right now and maintaining documentation in multiple languages would be a hard task to do hence why we are only defaulting to English for the time being. Imagine for example if Alex or someone that doesn't know arabic makes a completely new feature into tRPC and we have multiple translations of languages, we would need to call up everyone who knows each language, teach them about the new feature and hopefully if they have free time they will be able to write it in that language's docs or modify the existing one, this will generally slow down progress of introducing new things into the framework hence why we are choosing currently to not pursue with translations for the time being but we will always have it in plans for the future.

تحياتي من مصر ❤️

**Comment by a4addel** [comment]
> تحياتي من مصر ❤️

تحيا مصر يا عم الحاج

**Comment by dyaa** [comment]
لا، دا احنا نفتح فرع هنا بقي، صبحوا يا جدعان 😃

**Pull request closed without merging**
