### PR TITLE
update data-transformers docs

### PR DESCRIPTION
**Pull request by KATT**

### CODE REVIEW

**Review by simonedelmann — CHANGES_REQUESTED** [review]
You were faster than me with smartphone. :) 
You forgot to update the line `.transformer(superjson)`.

**Comment by KATT** [comment]
On my phone now, please update the pr 🙏

**Comment by simonedelmann** [comment]
Me too. ;) But I will update later today!

**Review by simonedelmann — APPROVED** [review]
Done! Feel free to merge whenever you want!

**Pull request merged**
