### PR TITLE
fix: enforce consistent type import/export

### PR DESCRIPTION
**Pull request by GerryWilko**
## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

This PR introduces the eslint rules:
```
'@typescript-eslint/consistent-type-imports': 'error',
'@typescript-eslint/consistent-type-exports': 'error',
```

These rules are already present in v11 of trpc and I have introduced them to v10 as well.

The rationale for this change is to assist with typecheck errors that may be flagged by third party frameworks like nuxt which need to include third party library types when building out some of the composable and component types for modules.

In my case Nuxt typecheck was flagging error `TS1484` in TRPC libraries. As Daniel Roe points out [here](https://github.com/nuxt/nuxt/issues/23609#issuecomment-1757283193). This can't be easily worked around in Nuxt.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
we already added this on next branch, and I don't want to deal with the conflcits this introduces when merging in main to next

**Comment by juliusmarminge** [comment]
> could main be merged before then all changes from this pr discarded when merging after?

I'm not sure i understand what you mean. We merge main into next regularily to bring changes over but all new features and such are pretty much on next now.

**Comment by GerryWilko** [comment]
> > could main be merged before then all changes from this pr discarded when merging after?
> 
> I'm not sure i understand what you mean. We merge main into next regularily to bring changes over but all new features and such are pretty much on next now.

i meant to just take local changes on next when merging this pr back over to the next branch once merged to main. if you can limit the merge queue to just this pr when merging into next as a once off then the conflicts can be resolved trivially no?

**Comment by juliusmarminge** [comment]
Maybe, we can try. Would you be up for doing the merge? You just run `pnpm merge-main` and then fix the conflicts, commit the merge and PR to next.

I made one now: https://github.com/trpc/trpc/pull/5299. So if you do it straight after this PR it should just contain these changes

**Comment by GerryWilko** [comment]
of course thats no problem. I'll wait for #5299 to merge and presumably this PR to merge just after? thanks for sorting this for me 😄

**Comment by juliusmarminge** [comment]
aight merging, if it doesn't work out we'll revert

**Comment by GerryWilko** [comment]
lovely sorry for the delay just popped out to walk the dog 😄 

this is the pr for merging this pr into next branch. https://github.com/trpc/trpc/pull/5301

as you can see it shows no file changes but the commit is included so think thats worked ok!

**Pull request merged**
