### PR TITLE
feat(`wsLink`): create async ws link (issue #4188)

### PR DESCRIPTION
**Pull request by spsDrop**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by KATT** [comment]
Would it be possible to do this without duplicating the wsLink and instead just have the existing one working with both clients? Will be less testing (although most of them could just be duplicated too)

**Comment by KATT** [comment]
Cool, I'm fine with that! We'll be doing next major soon as react-query 5 came out recently

**Comment by b0o** [comment]
We're using this and it seems to be working well so far, thank you @spsDrop!

**Review by KATT — CHANGES_REQUESTED** [review]
This still needs some tests 🙏 

Happy to merge it after

**Comment by spsDrop** [comment]
@KATT  I added a happy path test.

**Comment by KATT** [comment]
Sorry, we can't merge this when it makes the codecov drop this low and I do understand it's painful to add good test:

CleanShot 2023-06-22 at 11 22 43


I think a good course of action is to:

- Have a userland reference for this 
- Make a PR to the `next` branch to replace the existing link with the async one

Thoughts?

**Comment by spsDrop** [comment]
> * Have a userland reference for this

I think targeting next makes sense but I don't understand this line.

**Comment by juliusmarminge** [comment]
> I think targeting next makes sense but I don't understand this line.

I think what he means is to have some code-snippet in docs / example that people can copy-paste if they wanna do it in v10, and only do the "in-housed" implementation for v11 on the next branch

**Review by KATT — CHANGES_REQUESTED** [review]
Fails CI, please re-request review when it doesn't

**Comment by KATT** [comment]
cc @spsDrop are you planning on picking this up? Please close otherwise

**Pull request closed without merging**
