### PR TITLE
Improve WebSocket example design

### PR DESCRIPTION
**Pull request by toyamarinyon**
I tried to make the WebSocket demo looks like the Discord appearance.

## Sign Out

PC|Mobile
---|-------
CleanShot 2022-03-21 at 02 04 18@2x|CleanShot 2022-03-21 at 02 04 23@2x

## Sign In

PC|Mobile
---|-------
CleanShot 2022-03-21 at 02 07 23@2x|CleanShot 2022-03-21 at 02 07 24@2x

## Demo

https://user-images.githubusercontent.com/535254/159174245-b4c485c6-f2fd-4d44-8997-95e86dcb6b67.mp4

### CODE REVIEW

**Comment by toyamarinyon** [comment]
Fix the test because the E2E test is failing due to the repositioning of the text form.
(it's great that there is a test for example 👏 )

**Comment by KATT** [comment]
This is great!!! Thank you @toyamarinyon, if you setup github sponsors I'll send you some money :)

**Comment by KATT** [comment]
@all-contributors add @toyamarinyon for examples

**Review by KATT — APPROVED** [review]

**Comment by toyamarinyon** [comment]
> This is great!!! Thank you @toyamarinyon, if you setup github sponsors I'll send you some money :)

Thank you @KATT I setup github sponsors 😄 ⇒ https://github.com/sponsors/toyamarinyon

**Pull request merged**
