### PR TITLE
Websocket subscription optionally accepts input payload as function and re-evaluates on reconnect (#1574)

### LINKED ISSUE #1574: Reevaluate WebSocket Subscription Input Payload on Reconnection
I'm setting up a WS subscription was hoping that when the `trpcWsClient` reconnects it would re-evaluate the subscription payload, however this is not the case. 

**- Requirement**
  * Create trpc subscripion with { sessionId: null }
  * Server returns { data: { sessionId: 'abc123' } } to the client
  * Trpc connection dies due to bad network connection
  * Trpc reconnects & restablishes subscription with { sessionId: 'abc123' }

The code shown below is my current workaround:

```typescript
// client.ts
import type { Router } from 'apps/api/src';

import { createTRPCClient } from '@trpc/client';
import { createWSClient, wsLink } from '@trpc/client/links/wsLink';

const wsClient = createWSClient({ url: 'ws://localhost:8081' });

const trpcWsClient = createTRPCClient<Router>({
  links: [
    wsLink({ client: wsClient }),
  ],
});

let sessionId: string | null = null;

const subscribe = () => {
  const unsubcribe = trpcWsClient.subscription('session', { sessionId }, {
    onNext: (result) => {
      if (result.type === 'data') {
        sessionId = result.data.sessionId;
      }
    },
    onError: (error) => {
      console.error(error);
      unsubcribe();
      subscribe();
    },
  });
};

subscribe();
```

**- Solution proposal**
  * Modify the trpc client `.subscription` API
  * Can accept `TInput` **_or_** `() => TInput`
  * If input is function it is resolved on each reconnection

Example usage:

```typescript
// client.ts
import type { Router } from 'apps/api/src';

import { createTRPCClient } from '@trpc/client';
import { createWSClient, wsLink } from '@trpc/client/links/wsLink';

const wsClient = createWSClient({ url: 'ws://localhost:8081' });

const trpcWsClient = createTRPCClient<Router>({
  links: [
    wsLink({ client: wsClient }),
  ],
});

let sessionId: string | null = null;

trpcWsClient.subscription('session', () => ({ sessionId }), {
  onNext: (result) => {
    if (result.type === 'data') {
      sessionId = result.data.sessionId;
    }
  }
});
```

Let me know what you think @KATT

### PR DESCRIPTION
**Pull request by jlalmes**
This PR implements a backwards compatible way to optionally specify the subscription input payload as a function. The input value is resolved by this function each time the socket reconnects.

```
client.subscription('eventName', input, { ... })
// OR (now possible with this PR)
client.subscription('eventName', () => input, { ... })
```

These changes _do not_ affect the `useSubscription` hook in `@trpc/react`, only the raw `TRPCClient` from `@trpc/client`.

Closes #1574

### CODE REVIEW

**Comment by jlalmes** [comment]
It seems that one of the build jobs is timing out and therefore failing - Could you take a look @KATT ?
https://github.com/trpc/trpc/runs/5380102303

**Comment by jlalmes** [comment]
Just re-run the tests looks like it didn't timeout this time. Awaiting your feedback @KATT 👍

**Comment by KATT** [comment]
I still really struggle to see how this should be a client-side concern to keep track of? 🤔

**Comment by KATT** [comment]
I really appreciate you're doing this.

Maybe you can share more details of your use-case @jlalmes, and why this isn't something the server can pick up on it's own?

To me, it looks like something that the server should "know" after the createContext is called, which happens on first connect for WebSockets too.

**Comment by jlalmes** [comment]
Hi @KATT, thanks for getting back to me.

**_Use case_** - I am working on an internal web analytics tool:

- Client visits webpage for first time
- Client subscribes to server (via trpc) `input: { sessionId: null }`
- Server creates a session in the DB and returns the `sessionId` to the client
- Client saves this `sessionId` in `sessionStorage`
- Client navigates to a different page (causing page reload)
- Client subscribes to server `input: { sessionId: "abc123" }`

**_Reason for this PR_**

- If a client subscribes with `input: { sessionId: null }`
- A new session will be created on the server
- Then the client disconnects from the server due to bad network conditions
- When the client auto-reconnects (network connection reestablished) it will send `input: { sessionId: null }` again
- Another session will be needlessly created on the server

**_Why I propose this API_**

- See Reconnecting Websocket (`reconnecting-websocket`)
  - https://github.com/pladaria/reconnecting-websocket#update-url

Current workaround
```
const subscribe = () => {
  const unsubscribe = trpcWsClient.subscription('session', { sessionId: window.sessionStorage.getItem('session') }, {
    onNext: (result) => {
      if (result.type === 'data') {
        window.sessionStorage.setItem('session', result.data.sessionId);
      }
    },
    onError: (error) => {
      console.error(error);
      unsubscribe();
      subscribe();
    },
  });
};

subscribe();
```

Usage after this PR
```
trpcWsClient.subscription('session', () => ({ sessionId: window.sessionStorage.getItem('session') }), {
  onNext: (result) => {
    if (result.type === 'data') {
      window.sessionStorage.setItem('session', result.data.sessionId);
    }
  }
});
```

Let me know if this is not clear.

Thanks

**Comment by KATT** [comment]
Hmmm.. is there a reason why you aren't using a session cookie? Cookies are usually the way to deal with this on the web

**Comment by jlalmes** [comment]
Fair point I suppose, closing this PR & issue for now.

**Comment by KATT** [comment]
I really appreciate the work you did on this @jlalmes, feel free to reopen a discussion about it if you feel it's something we should support!

**Pull request closed without merging**
