### PR TITLE
Bump react-ssr-prepass to 1.5.0

### PR DESCRIPTION
**Pull request by MarcGuiselin**
Fixes https://github.com/trpc/trpc/issues/1343

### CODE REVIEW

**Comment by KATT** [comment]
On my phone so can't answer properly. 

What I mean is that you should push a branch to the trpc repo rather than your fork and then open a PR from that 😅

**Comment by KATT** [comment]
Oh yah, this looks right

**Review by KATT — APPROVED** [review]

**Comment by KATT** [comment]
Or no, it should be from a branch on trpc origin (not your fork) towards a main branch in trpc ☺

**Comment by MarcGuiselin** [comment]
Ahhh, ok. Whoops 😀 I'll do that when I get back to my PC.

**Pull request closed without merging**
