### PR TITLE
feat: uwebsockets.js support

### PR DESCRIPTION
**Pull request by yovanoc**
## 🎯 Changes

Support using uWebsockets.js.

Usage:

```ts
import { createUWebSocketsHandler } from '@trpc/server/adapters/uwebsockets/http';
import { applyWSSHandler } from '@trpc/server/adapters/uwebsockets/ws';
import { app } from '../config.js';
import { appRouter } from './root.js';
import { createContextHttp, createContextWS } from './context.js';

createUWebSocketsHandler(app, '/trpc', {
  router: appRouter,
  createContext: createContextHttp,
});

export const { broadcastReconnectNotification } = applyWSSHandler({
  app,
  prefix: '/trpc',
  router: appRouter,
  createContext: createContextWS,
});

```

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by sachinraja** [comment]
I don't think we can add this to code because of the maintenance burden and I don't think any of us on the core team are familiar with uwebsockets.

This is great work though and I would encourage you to publish this as a separate package!

**Comment by yovanoc** [comment]
> I don't think we can add this to code because of the maintenance burden and I don't think any of us on the core team are familiar with uwebsockets.
> 
> This is great work though and I would encourage you to publish this as a separate package!

Oh ok, no problems but I can't because some files are not exported..or I have to copy paste a lot from internals...is there a way to export it then ? thanks

- https://github.com/trpc/trpc/blob/main/packages/server/src/error/utils.ts
- https://github.com/trpc/trpc/blob/main/packages/server/src/internals/types.ts
- https://github.com/trpc/trpc/blob/main/packages/server/src/http/internals/types.ts
- https://github.com/trpc/trpc/blob/main/packages/server/src/internals/transformTRPCResponse.ts
- https://github.com/trpc/trpc/blob/main/packages/server/src/transformer.ts
- https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/node-http/types.ts

**Comment by juliusmarminge** [comment]
> > I don't think we can add this to code because of the maintenance burden and I don't think any of us on the core team are familiar with uwebsockets.
> 
> > 
> 
> > This is great work though and I would encourage you to publish this as a separate package!
> 
> 
> 
> Oh ok, no problems but I can't because some files are not exported..or I have to copy paste a lot from internals...is there a way to export it then ? thanks
> 
> 
> 
> - https://github.com/trpc/trpc/blob/main/packages/server/src/error/utils.ts
> 
> - https://github.com/trpc/trpc/blob/main/packages/server/src/internals/types.ts
> 
> - https://github.com/trpc/trpc/blob/main/packages/server/src/http/internals/types.ts
> 
> - https://github.com/trpc/trpc/blob/main/packages/server/src/internals/transformTRPCResponse.ts
> 
> - https://github.com/trpc/trpc/blob/main/packages/server/src/transformer.ts
> 
> - https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/node-http/types.ts

Make a PR exporting what you need 👍

**Comment by yovanoc** [comment]
Perfect, thank you a lot I do this today :)

**Pull request closed without merging**
