### PR TITLE
chore: remove prisma overrides script

### PR DESCRIPTION
**Pull request by KATT**
Closes #

## 🎯 Changes

@helmturner reported issues installing trpc [here](https://github.com/trpc/trpc/pull/5713#issuecomment-2132064145)  and while I think this is a user error it prompted me to look a bit.

I have forgotten why we have these really, they got added in #2871 by @sachinraja and the issue they fixed might have fixed itself by now [almost two years later]. I also think they're the cause of why our `next-prisma-starter` fails to deploy _sometimes_.

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
iirc it's cause prisma kind of sucked in monorepos before so we did this to ensure there are separate PrismaClient's

**Comment by juliusmarminge** [comment]
I havent used Prisma for a while so not sure what the current state of it is

**Comment by helmturner** [comment]
Definitely user error. This still fails to run for me but this time with `ERROR: "codegen:entrypoints" exited with 1.`

My system is, for some reason, unable to execute the Turbo Mach-o binary. 
```sh
│   x failed to execute local turbo process
│   `-> Malformed Mach-o file (os error 88)
```

**Comment by helmturner** [comment]
Turns out it was a corrupted PNPM cache. `pnpm prune` did the trick.

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
