### PR TITLE
[DO NOT MERGE] Test

### PR DESCRIPTION
**Pull request by swarnava**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by KATT** [comment]
CleanShot 2023-02-03 at 00 23 04@2x

:(

**Comment by janory** [comment]
Hi @KATT @swarnava! 👋 
As far as I can see we are dealing here with 4 different projects/deployments: `www`, `todomvc`, `next-prisma-starter`, `og-image`.

- From the 4 projects the `todomvc` don't require auth and the deployment completes, which is the expected behaviour.
- The `next-prisma-starter` and the `og-image` projects have sensitive environment variables, therefore the required authorization is actually the correct behaviour as well.
- The `www` project doesn't have sensitive environment variables, but it still (incorrectly) requires authorization.

So we are focusing on the `www` project and investigating what's the issue there.
@KATT can you please verify that the auth logic works as designed for the rest of the projects?

**Comment by KATT** [comment]
> So we are focusing on the `www` project and investigating what's the issue there. @KATT can you please verify that the auth logic works as designed for the rest of the projects?

Yeah, it does work as expected for the rest, `www` suddenly stopped working even if it has no env variables around the same time as this announcement: https://vercel.com/blog/protecting-deployments

**Comment by swarnava** [comment]
We have pushed a possible fix for this. Can you try now?

**Comment by KATT** [comment]
Awesome, whatever you did seems to have fixed it! Thank you very much

**Pull request closed without merging**
