### PR TITLE
Fix disabled query SSR and add tests

### LINKED ISSUE #621: @trpc/react trpc.useQuery ignores enabled: false during SSR
The issue seems to be that it doesn't check for `opts?.enabled !== false` here:
https://github.com/trpc/trpc/blob/438c06d90a1a5c358468424860b4384675d5154e/packages/react/src/createReactQueryHooks.tsx#L211-L218

### PR DESCRIPTION
**Pull request by hypnodron**
Closes #621 

When writing tests I've encountered two different behavior depending on whether the `queryKey` changes or not and documented both of them in tests.

### CODE REVIEW

**Comment by KATT** [comment]
Awesome, thanks!! Could you add it to the infinite query too (if they have that prop; I'm on my phone reviewing this)

**Comment by hypnodron** [comment]
Fixed the issue for infinite query and added tests. 

Also I added options forwarding from `useQuery` to `fetchQuery`. I could not figure out the types so I casted the options to any for now. Even though `react-qeury`'s `fetchQuery` accepts only subset of options of `useQuery`, forwarding them directly seems fine and `react-qeury` just ignores excess options.

**Comment by KATT** [comment]
Out hiking 🗻 will merge ASAP. Thanks so much for being so thorough.

**Review by KATT — APPROVED** [review]

**Comment by KATT** [comment]
Thank you so much for this @hypnodron!!

**Comment by KATT** [comment]
@all-contributors please add @hypnodron for tests and code

**Pull request merged**
