### PR TITLE
Fix: Detect and support APIGatewayProxyEvent isBase64Encoded

### PR DESCRIPTION
**Pull request by eliotlim**
Hi @trpc team!

I started using tRPC recently, and found it pretty magical. Just wanted you to know that what you're working on is very cool. While giving it a spin, something came up.

It turns out that request bodies of mutations (POST) may get base64-encoded by the API Gateway Lambda Proxy integration. When that happens, a TRPCClientError like this will be thrown:

```
TRPCClientError: Unexpected token e in JSON at position 0
{
    message: 'Unexpected token e in JSON at position 0',
    code: -32700,
    data: {
      code: 'PARSE_ERROR',
      httpStatus: 400,
      stack: 'TRPCError: Unexpected token e in JSON at position 0\n' +
        '    at getRawProcedureInputOrThrow (/var/task/dist/index.js:34581:11)\n' +
        '    at Object.resolveHTTPResponse (/var/task/dist/index.js:34661:22)\n' +
        '    at Runtime.handler (/var/task/dist/index.js:33467:48)\n' +
        '    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1028:29)'
    }
}
```

Although correctly setting the `content-type` should prevent payloads from being base64 encoded ([v9](https://github.com/trpc/trpc/blob/e0abf0deb3a69e0be0f3ec1bba03d5ef43e50b34/packages/client/src/internals/httpRequest.ts#L63), [v10](https://github.com/trpc/trpc/blob/50d151ed196bfff5cde03740b0467b5158f57959/packages/client/src/links/internals/httpUtils.ts#L136)), it seems that the adapter should still detect and decode payloads based on the `isBase64Encoded` flag in `APIGatewayProxyEvent`.

The key observation is that base64 encoded JSON values (`{"`) begin with `eY...`, which explains the error `TRPCError: Unexpected token e in JSON at position 0`.

I've written a simple change and a test case to verify that payload decoding works correctly. It seems to behave correctly on a tRPC lambda deployment I'm currently working on as well.

Thanks again for taking time to read this and maintain tRPC. If I could be of help to backport this fix to v9 as well, please let me know.

## 🎯 Changes

+ Decode event payload if `isBase64Encoded`
+ Add awsLambda adapter test case using tRPC mutations (POST)
+ Add utility wrapper which mocks base64-encoded requests

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by Lilja — APPROVED** [review]
Nice catch! I recently ran into this issue myself when having the swedish letters ÅÄÖ in a json-payload in a go-lambda.
Looks good, let's run the tests.

**Comment by eliotlim** [comment]
> Looks good, let's run the tests.

It seems as though we'll need approval to run this check: `Vercel – next-prisma-starter — Authorization required to deploy.`
Would you be able to help with that, please?

**Comment by Lilja** [comment]
@KATT could you help us run tests?

**Comment by Lilja** [comment]
I'm afraid you might need to be a contributor and upload a branch to this tree as opposed to your fork. But let's see what Alex says.

**Comment by Lilja** [comment]
I'm afraid you might need to be a contributor and upload a branch to this tree as opposed to your fork. But let's see what Alex says.

**Review by KATT — CHANGES_REQUESTED** [review]
Thanks for your contribution! :pray: :pray: 

I've added you as a contributor now, could you please do the following for me? :point_down:

1. Accept the invitation - [link](https://github.com/trpc/trpc/invitations)
1. Push your branch to `origin` / `git@github.com:trpc/trpc.git`
1. Open a new PR from origin instead
1. Close this PR

This is in order for CI to run properly so we can get all those nice ✅ ahead of merging.

I really appreciate you spending time helping out with tRPC, feel free to continue to do so. All contributions are welcome, big or small!

**Comment by Lilja** [comment]
I see [this](https://i.imgur.com/HH4hilC.png) but I just get redirected when i press it.

**Comment by KATT** [comment]
Yeah I can autorize vercel but not the ci runs within github so that doesn't matter

**Comment by eliotlim** [comment]
Okay, I've created #3040 to continue this thread / discussion.

**Pull request closed without merging**
