### PR TITLE
Content sliders.

### PR DESCRIPTION
**Pull request by anthonyshew**
## 🎯 Changes

[Content Rules Everything Around Me](https://www.google.com/search?q=content+rules+everything+around+me&oq=content+rules+everything+around+me&aqs=chrome..69i57.5343j0j4&sourceid=chrome&ie=UTF-8)

Let's try to showcase efforts by the community a little better! I looked at this on mobile, tablet, and desktop sizes but let me know if I missed something.

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/next/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Spacing on top right card looks a bit off 
CleanShot 2022-11-19 at 16 08 51@2x

**Review by sachinraja — COMMENTED** [review]
I like this, I want to do something like https://www.solidjs.com/ecosystem for the extensions and examples too at some point.

**Comment by anthonyshew** [comment]
Huh, that author text isn't really striking me as awkward, @juliusmarminge. I don't really know what else I would do with it. 🤔

**Comment by juliusmarminge** [comment]
> Huh, that author text isn't really striking me as awkward, @juliusmarminge. I don't really know what else I would do with it. 🤔

Yea me neither it's probably just that it's the only one that caught my eye

**Review by sachinraja — APPROVED** [review]

**Pull request merged**
