### PR TITLE
docs(awesome-trpc): added `sidebase` to awsome trpc

### PR DESCRIPTION
**Pull request by zoey-kaiser**
Closes none

## 🎯 Changes

Hello tRPC team 👋 
This PR adds [`sidebase`](https://sidebase.io) to the list of projects and developer tools that use tRPC. sidebase is a Nuxt 3 stack with its own CLI to quickly help bootstrap a Nuxt 3 application. We recommend tRPC in our stack and think it would be amazing to offer a Nuxt solution on awsome tRPC!

## ✅ Checklist

- [X] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [X] If necessary, I have added documentation related to the changes made.
- [X] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — DISMISSED** [review]

**Comment by KATT** [comment]
If you fix lint i'll merge @zoey-kaiser :)

**Comment by zoey-kaiser** [comment]
> If you fix lint i'll merge @zoey-kaiser :)

Hi @KATT 👋 thanks for being so quick. 
I ran `pnpm lint-fix` and no errors popped up on my system. When checking the logs for the lint [here](https://github.com/trpc/trpc/actions/runs/4225808529/jobs/7338540021). Do you have any tips for me where to check

**Comment by juliusmarminge** [comment]
> > If you fix lint i'll merge @zoey-kaiser :)
> 
> 
> 
> Hi @KATT 👋 thanks for being so quick. 
> 
> I ran `pnpm lint-fix` and no errors popped up on my system. When checking the logs for the lint [here](https://github.com/trpc/trpc/actions/runs/4225808529/jobs/7338540021). Do you have any tips for me where to check

The lint-fix doesnt run prettier. Run `pnpm format` and it should fix it for you

**Comment by zoey-kaiser** [comment]
Thanks @juliusmarminge that did the trick! @KATT linting is now fixed 🥳

**Review by juliusmarminge — APPROVED** [review]

**Comment by zoey-kaiser** [comment]
Thanks @juliusmarminge and @KATT for your quick help! ❤️

**Pull request merged**
