### PR TITLE
issue #5217 update docusaurus to v3

### PR DESCRIPTION
**Pull request by spk-krishna567**
#5217 
according to Docusaurus has released v3: https://docusaurus.io/blog/releases/3.0.

I had updated version v3

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
Does this build for you locally? It fails on the preview

**Comment by KATT** [comment]
Maybe a pnpm install is enough

**Comment by spk-krishna567** [comment]
I did pnpm install already

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this PR.

#5387 is further along with doing this migration - it's not only about updating the dependencies, it's a bit more involved. Please help out over there! 🙏

**Pull request closed without merging**
