### PR TITLE
feat: simplifies pnpm setup

### PR DESCRIPTION
**Pull request by ixahmedxi**
## 🎯 Changes

This pull request does the following changes:

- adds `engine-strict=true` to the `.npmrc` file so that we fail if an incompatible version of node is used.
- removes `strict-peer-dependencies=false` from the `.npmrc` file as that this is the default
- adds `prefer-workspace-packages=true` to the `.npmrc` file instead of manual links in the root `package.json`
- adds pnpm to the `engines` field in the `package.json` file.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by KATT** [comment]
cc @ixahmedxi are you planning on working on this? :)

**Review by KATT — COMMENTED** [review]
Just leaving a comment so it doesn't appear in my review request inbox, feel free to re-request review if you pick this up again (or close it if you're not planning to :))

**Comment by ixahmedxi** [comment]
> cc @ixahmedxi are you planning on working on this? :)

Yes I am, just busy with my final exams right now but I will pick it up again after :)

**Review by juliusmarminge — APPROVED** [review]

**Comment by juliusmarminge** [comment]
Feel free to do follow-ups if there was stuff left to do @ixahmedxi

**Pull request merged**
