### PR TITLE
chore: stricter checks for tRPC-like responses

### LINKED ISSUE #3359: bug: TRPCClientError.from() fails to some handle responses gracefully (ex. 413 Request body is too large)
### Provide environment information

Client 

```
  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 43.13 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.12.1 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Safari: 16.1
  npmPackages:
    @tanstack/react-query: ^4.19.1 => 4.19.1
    @trpc/client: ^10.4.3 => 10.4.3
    @trpc/react-query: ^10.4.3 => 10.4.3
    @trpc/server: ^10.4.3 => 10.4.3
    react: ^18.2.0 => 18.2.0
    typescript: ^4.9.4 => 4.9.4
```

Server

```
  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 48.50 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.12.1 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Safari: 16.1
  npmPackages:
    @trpc/server: ^10.4.3 => 10.4.3
    typescript: ^4.9.4 => 4.9.4
```

### Describe the bug

Our client is using `httpBatchLink` and we are encountering an issue when the server determines that the request body is too large. This issue is in regard to how the client handles it.

## Some background

The response from the server is 

image

With a body: 

```json
{
  "statusCode":413,
  "code":"FST_ERR_CTP_BODY_TOO_LARGE",
  "error":"Payload Too Large",
  "message":"Request body is too large"
}
```

The error we get in bubbling up is:

```
TRPCClientError: Cannot read properties of undefined (reading 'message')
    at TRPCClientError.from (transformResult-4e0db787.mjs:13:16)
    at httpBatchLink.mjs:200:64
```

Where I expect the error to be more like "Request body is too large" or something

## Further debugging

If we put a breakpoint in `TRPCClientError.from` we see the following:

image

## Suggested fix

One suggestion could be to change https://github.com/trpc/trpc/blob/d12ae145922a793d5234cc3023c283064e1c12ab/packages/client/src/TRPCClientError.ts#L64

to

```ts
cause.error?.message ?? cause.message ?? '' // cause.message will be "Request body is too large"
```

### Link to reproduction

Hopefully the description above explains it good enough

### To reproduce

Hopefully the description above explains it good enough

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by thhermansen**
Closes #3359

## 🎯 Changes

TRPCClientError.from supports receiving error where cause.error is not an object.

Maybe a better fix could have been to be even more uncertain with the cause's type? Setting it to unknown and letting the runtime code be even more defensive.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
Thanks for this and especially for the regression test!

I changed the "fix" a bit - the issue, as I see it, is not that we're not handling ambiguous responses, the problem is that we don't validate well enough that the response is a "TRPC Response". I've done that now as part of the transformation step, let me know if this makes sense to you, @thhermansen

**Review by KATT — APPROVED** [review]

**Comment by thhermansen** [comment]
Thank you. Seems reasonable :)

**Comment by thhermansen** [comment]
@KATT - a question related to this PR:

Normally when we get a well formatted TRPC response with an TRPC error it seems like we get access to the response in `error.meta.response`:

image

But when requests fails on the http transport layer, as an example cos the http server responded with is 503 or 429 we get nothing passed in the `error.meta.response`. Only the error message message `Badly formatted response from server` bubbles up to our code from trpc. 

Do you think it is a good idea to add the underlaying response on this error too? That could help the error handler provide a more specific error message to the user based on the underlaying http response.

**Comment by thhermansen** [comment]
@KATT - Happy new year 🎉 Just a friendly reminder if you got time to [look at this](https://github.com/trpc/trpc/pull/3365#issuecomment-1350811029) ☝️

**Comment by KATT** [comment]
Yes @thhermansen, that would be good 👍 feel free to do a PR

**Comment by KATT** [comment]
Discussions on closed issues get missed very easily, make an issue or a discussion next time 🙏 ☺

**Pull request merged**
