### PR TITLE
Added uWebSockets adapter

### PR DESCRIPTION
**Pull request by romanzy-1612**
Adapter for [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js)

Everything works, except the res object in the context (see notes in adapter code). Also, there are some questions in code regarding potential issues/weirdness.

BTW, need a better name for registration function. Currently its `registerTRPCasUWebSocketsEndpoint` 🥴

### CODE REVIEW

**Comment by jlalmes** [comment]
Thanks for the PR @romanzy-1612!

I think this adapter should probably be released as it's own package (something like `trpc-uwebsockets`) so that the tRPC team aren't left to maintain. You're probably already aware, but we support already supports native WebSockets out of the box.

I've never actually seen [`uWebSockets.js`](https://github.com/uNetworking/uWebSockets.js) before, it seems to be a super impressive node WebSocket implementation from the performance benchmarks.

**Review by KATT — CHANGES_REQUESTED** [review]
Hey! Thank you so much for your contribution!

We aren't currently accepting big changes into the `main` branch as we're hard at work with the `next`-branch (new major coming soon! 🥳)

Unfortunately, we haven't _properly_ fixed the support for subscriptions on the next major yet (#2114), but contributions are welcome.

Feel free to change your suggested changes `main` to `next` and we'll happily take a look at it. 

Furthermore:

Thanks for your contribution! :pray: :pray: 

1. Accept the invitation - [link](https://github.com/trpc/trpc/invitations)
1. Push your branch to `origin` / `git@github.com:trpc/trpc.git`
1. Open a new PR from origin instead
1. Close this PR


I really appreciate you spending time helping out with tRPC, feel free to continue to do so. All contributions are welcome, big or small!

**Comment by KATT** [comment]
Also, I'm not sure if we want to support more adapters, we have one for `ws` that works, but you could release a `trpc-uwebsockets` package? Is there any internals that you need to access?

**Comment by romanzy-1612** [comment]
Only internals needed are types, which can be easily imported. As per your suggestions, I have published it as [trpc-uwebsockets](https://www.npmjs.com/package/trpc-uwebsockets). Only 2 new files are added, and they should be independent from the rest of the code.

uWebsockets, despite its name, is also a really good HTTP server with scalable pub-sub. Static file and SSL performance is phenomenal. It is not very popular because it exposes a much lower level API then express. But with tRPC it is easy to use!

**Comment by KATT** [comment]
Nice! Add it to the awesome trpc collection in `/www` ☺ 🙏 ♥

**Pull request closed without merging**
