### PR TITLE
bug: inline sub-routers with react

### PR DESCRIPTION
**Pull request by KATT**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by KATT** [comment]
cc whoever who is watching (prob @Nsttt) I fixed some of them I think, but there are some left. 

- I've fixed a few
- Looks like we're needlessly passing `TRouter` around (we can infer `TRPCClientError`s off procedures
- Still a bunch of refactoring to do  - looks like a bunch of places should change from taking an `AnyRouter` to a `ProcedureRouterRecord`
- In the end, I think the code is going to be cleaner as a result of all of this refactoring
- We might need to look at the end to make sure no `@public`-marked types are changed

**Comment by Nsttt** [comment]
Sure, been checking some of the issues. I'll start from the /proxy and will go down changing some of the AnyRouters.

I'll ping if I'm unsure of anything.

**Comment by KATT** [comment]
> Sure, been checking some of the issues. I'll start from the /proxy and will go down changing some of the AnyRouters.
> 
> I'll ping if I'm unsure of anything.

Cool, I've commented out the feature for now in the docs so hopefully nobody tries to use it 😅

**Comment by KATT** [comment]
If you can clone this branch you can see that it's _partly_ fixed

CleanShot 2023-03-16 at 08 07 28@2x


Feel free to change whatever so it makes sense to you

**Comment by Nsttt** [comment]
Okey, seems another one fixed with this, I need to account for the last one and maybe improve the naming and nesting of conditionals.

**Comment by Nsttt** [comment]
Having a few errors locally related to this. Not sure if this is me.

CleanShot 2023-03-26 at 19 01 46

**Comment by kamilogorek** [comment]
```
[test-run:vitest]  ✓ tests/server/react/bigBoi.test.tsx  (2 tests) 704ms
[test-run:vitest]  ✓ tests/server/react/interopBig.test.tsx  (2 tests) 3650ms
```

Works for me locally on this very branch.

**Pull request closed without merging**
