### PR TITLE
chore: add `eslint-plugin-prettier` to eslint

### PR DESCRIPTION
**Pull request by iduuck**
Closes nothing.

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

**Be sure that this is a very opinionated PR, but fixed DX for vim users.**

I added the `eslint-plugin-prettier` plugin to the repository, since the formatting is not available throughoutly in (n)vim. 

Auto-format on save is not available to nvim without needing a lot more plugins, etc.

Be sure to close, when not needed/wanted.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Rationale for switching: https://github.com/trpc/trpc/pull/3501

**Comment by iduuck** [comment]
Good thing I am bringing this back up again.

I think this is (as prev said) a very opinionated thing. I am using an fix on save workflow personally, so I am more than happy to have the red/yellow squiggles. But yeah, depends on the workflow of the individual developers.

**Comment by juliusmarminge** [comment]
You should add `formatOnSave` too if you want to format on save - I know some peopel don't like that so it's good that they're separate IMO

**Comment by iduuck** [comment]
That's actually what I am doing, hence only typescript/eslint issues are being left, after formatted on save (for prettier)

**Comment by juliusmarminge** [comment]
Oh maybe i misunderstood. Then its `eslint.fixOnSave` you want?

**Comment by iduuck** [comment]
That's already working for me, @juliusmarminge. But without the prettier plugin, the auto-fix isn't working for me on the repo. I need to also have an LSP for neovim for prettier.

But this is a fundamental thing, cause linzer (in nvim) take 100x the time than the eslint fixing.

**Review by KATT — COMMENTED** [review]
@juliusmarminge I'm fine with this, do you wanna merge this?

I'd like it to be accessible to vim people :)

**Review by juliusmarminge — DISMISSED** [review]

**Comment by sachinraja** [comment]
> But without the prettier plugin, the auto-fix isn't working for me on the repo. I need to also have an LSP for neovim for prettier.

Why are you not using the prettier plugin for nvim?

**Review by KATT — APPROVED** [review]

**Pull request merged**
