### PR TITLE
feat/Who's using tRPC

### LINKED ISSUE #1290: 👋 Who's using tRPC?
Drop your company name, svg logo, link to your website, and links to any repos using tRPC! 🙌

Some companies / sites I know myself

- 🥇  [cal.com](https://cal.com) - Scheduling startup, [it's open source!](https://github.com/calcom/cal.com)
- 🥈 [ping.gg](https://ping.gg) - A better way to stream with friends (YC W22)
- 🥉  [interval.com](https://interval.com)
- 🥉 [newfront.com](https://newfront.com) - Insurance startup (YC W18 & a [unicorn 🦄](https://www.crunchbase.com/organization/abe-4) )
- 🥉 [snaplet.dev](https://snaplet.dev) - Snaplet copies your prod database, transforming PII-data, so you can code against actual data
- [Netflix](https://netflix.com/) 🦄 
- [hidrb.com](https://hidrb.com/) - Healthcare / covid vaccination booking systems
- [vembla.se](https://vembla.se) - Grocery delivery app (uses tRPC in React Native 📱)
- [memorylanegames.com](https://www.memorylanegames.com/) (uses tRPC in React Native 📱)
- [inv.tech](https://inv.tech) 
- [napo.pet](https://www.napo.pet/) 
- [pleo](https://www.pleo.io) [🦄 ]

<sub>[TRP-64](https://linear.app/trpc/issue/TRP-64/👋-whos-using-trpc)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/1290">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/1290/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by kwaimind**
Hey tRPC team, 

I took a look at #1290 and tried to build it as a feature for the www landing page to show who is using tRPC. 

I wanted to bring a list of company logos to the landing page for social proof, and to bring this github issue/discussion to life for future devs. I didn't add all logos, and wanted to get feedback on if this is a direction the www team wants to take.

If I missed the point here and #1290 is supposed to be a discussion and not a feature, then just let me know 🫡

**Input needed**: Looking for suggestions on the text, which is currently:

_Headline:_ As used by
_Description:_ tRPC is tried and trusted by leading tech teams

We should also agree on if logos should follow some kind of template, and if they should be in colour or black?

Closes #1290

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

- Feature to add "companies using tRPC" to the homepage
- Tailwind animated "carousel" of svgs/pngs

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
~~I have added or updated the tests related to the changes made.~~

### CODE REVIEW

**Comment by juliusmarminge** [comment]
I think it's a nice addition

Contrast definitely needs fixed though:

CleanShot 2023-12-13 at 18 49 18@2x

**Comment by kwaimind** [comment]
> I think it's a nice addition
> 
> Contrast definitely needs fixed though:
> 
> CleanShot 2023-12-13 at 18 49 18@2x

Great point, that's my bad. I went ahead and:
1. converted all svgs to black & optimized them
2. inverted the svg when in dark mode with css

Let me know what you think

**Review by KATT — APPROVED** [review]
Looks great, thank you!

**Comment by kwaimind** [comment]
Tackar tackar 🫡

**Pull request merged**
