### PR TITLE
ci: add support for changesets

### LINKED ISSUE #162: Fix changeset
Using https://github.com/atlassian/changesets

... but didn't get it working properly. Someone could probably fix this.

### PR DESCRIPTION
**Pull request by ifiokjr**
This adds support for automated releases via changesets. I've set up similar flows with https://github.com/remirror/remirror and https://github.com/monots/monots.

I've kept the changes to a minimum since it touches some sensitive code areas. 

- Closes #162
- Replaces #1050

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
This looks great, a few questions below!

- What bot should I add to make sure PRs have changesets?
- What do I need to configure for the releases?
- Does it actually do patch/minor/major/etc automatically?

**Comment by KATT** [comment]
It was a long time since I tried to get automatic changeset in so appreciate any guidance! :pray:

**Comment by ifiokjr** [comment]
> What bot should I add to make sure PRs have changesets?

Install the [changesets bot](https://github.com/apps/changeset-bot). Details on exactly what it does are provided in the linked description.

> What do I need to configure for the releases?

The configuration is mostly done. Here's the current flow I've opted for.

- A pull request with a new feature is created.
- The installed [bot](https://github.com/apps/changeset-bot) reminds the user to add a changeset if it's not already created.
 - Changesets can also be added from the command line via `yarn changeset`. The script looks at what's changed in the current branch since `main`, and allows the user to select the packages their changes describe.
- After the PR is merged into `main`, the changesets action is run. It uses the trigger `workflow_run` which waits for the `Build & Test` workflow to succeed before starting. 
 - I would advise grouping your core CI actions into one workflow, so that releases only happen when everything passes (tests, linting, typechecking, integration tests etc...). I don't think you can currently wait on multiple `worflow_run` events with `AND` logic rather than `OR`, I may be wrong though.
- The action automatically detects whether there are any changesets that haven't yet been released. If this is the case it will create a pull request which updates the CHANGELOG files and package versions.
 - This PR should be inspected in case of unexpected versioning. 
 - The PR will automatically be updated when the `main` branch changes.
- Once happy with the changes the automatically created PR can be merged into main. 
- The `changesets` actions is run again and this time it notices that the workspace packages have a higher version than the packages on NPM.
- The release command is run. It firstly adds the release to NPM and then creates GitHub releases matching the changes described in the merged `changesets` PR.

> Does it actually do patch/minor/major/etc automatically?

Yes 🥳 

Based on the type of change specified via `yarn changeset`. Changesets handles the rest.

### Versioning

Here are some additional considerations.

Using changesets will change the way the repo is tagged and versioned. Right now, you are using a single version `v9.9.0`. In contrast, changesets creates a tag for each package that is released. This would mean that your `v9.9.0` release would be split into 4 tags: 
- `@trpc/server@9.9.0`
- `@trpc/client@9.9.0`
- `@trpc/next@9.9.0`
- `@trpc/react@9.9.0`

Since `trpc` consists of 4 packages, the noisiness of releases is relatively low. In https://github.com/remirror/remirror there are more than 100 packages. As a result, there is a custom script to automatically create GitHub releases for the key packages `@remirror/react` and `remirror`. Changesets doesn't currently have that functionality.

**Would you like to generate GitHub releases for all 4 packages or limit them to a subset?**

By default, `changesets` versions packages independently. In contrast, `trpc` every package is updated to the same version at release, anytime anything changes.

**Do you want versions to continue to be linked together, or would you like versions to be independent?**

**Comment by KATT** [comment]
It seems to have gotten a bit mad after merging your other PR #1056 - see #1070 etc so I deleted it in #1071

I have a "bot"-user that I would like to do the PR (`TRPC_GITHUB_TOKEN` / `NPM_TOKEN`)

> Would you like to generate GitHub releases for all 4 packages or limit them to a subset?

This is fine! I like to have all the packages coupled for now

> Do you want versions to continue to be linked together, or would you like versions to be independent?

I want them all linked for now!

**Comment by KATT** [comment]
Feature creep, it would be awesome to get the `/README.md` part of each npm-package

**Comment by ifiokjr** [comment]
> This is fine! I like to have all the packages coupled for now

Just to clarify, this ensures all versions are released together, however the tags will still be prefixed with the package name. You will go from one tag per release to 4.

**Comment by ifiokjr** [comment]
> Feature creep, it would be awesome to get the `/README.md` part of each npm-package


I'm not sure what you mean by this.

**Pull request closed without merging**
