### PR TITLE
fix: declare ctx before using it in ws.ts

### PR DESCRIPTION
**Pull request by tychenjiajun**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
Did a typo

**Comment by KATT** [comment]
What are you trying to fix here?

We are changing the behavior of this so context is sometimes created after the first message (that can be authentication params) in #5875

**Comment by tychenjiajun** [comment]
> What are you trying to fix here?
> 
> We are changing the behavior of this so context is sometimes created after the first message (that can be authentication params) in #5875

Thank you for your reply!

I am using a 'fake WebSocket' in my project to communicate between SharedWorker and Windows. It works fine in Firefox and Chrome but has `TRPCClientError: Cannot access uninitialized variable` on some old WebKit-based browsers. This is what I'm tring to fix.

**Comment by tychenjiajun** [comment]
I solve my problem by changing one line

```diff
- this.eventEmitter.emit('connection', client, { url: 'https://example.com });
+ this.eventEmitter.emit('connection', client, { url: 'ws://example.com/?connectionParams=1' });
```

**Pull request closed without merging**
