### PR TITLE
remove “Dependabot auto-approve” workflow

### PR DESCRIPTION
**Pull request by iduuck**
## 🎯 Changes

- remove dependabot approval workflow
- workflow not needed anymore, since we are using kodiak
- kodiak is automatically approving, and when necessary merging the changes

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
I think I can't set kodiak as a codeowner tho so it won't auto-merge

**Comment by iduuck** [comment]
I don't really understand. Kodiak has "auto-merge" functionality, and it doesn't need to be CODEOWNER for this.

So, actually I don't know nothing about **this repos** branch protection, but normally it should be possible to "auto-approve" the PR with Kodiak, and also auto-merge with Kodiak.

**Comment by KATT** [comment]
> I don't really understand. Kodiak has "auto-merge" functionality, and it doesn't need to be CODEOWNER for this.
> 
> So, actually I don't know nothing about **this repos** branch protection, but normally it should be possible to "auto-approve" the PR with Kodiak, and also auto-merge with Kodiak.

We require code owners to approve in order to merge and AFAIK I can't set an _actual_ bot like kodiak to be a codeowner


Our branch protection settings for reference:

Screenshot 2022-10-09 at 12 10 07

**Comment by iduuck** [comment]
From googling on my phone (not near a computer right now), I found this story from FullStory: https://www.fullstory.com/blog/taming-github-codeowners-with-bots/

They claim, that it is possible to assign bots to a group, and assign the group as a "codeowner" - perhaps give this a try.

**Pull request closed without merging**
