### PR TITLE
Fix www navbar responsiveness

### LINKED ISSUE #3340: bug: (minor bug) Navbar of the website is a bit messy in some viewport widths
### Provide environment information

Not applicable.

### Describe the bug

image

I regularly use my browser at this viewport size, so seeing the navbar like that makes me a bit uneasy... Also the problem is worse for some smaller viewport size as well:

image

### Link to reproduction

https://github.com/trpc/trpc

### To reproduce

* Visit trpc.io
* Resize your browser window width

### Additional information

* Browser: Safari 16.1

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by neo773**
Closes #3340

## 🎯 Changes

This PR fixes issue https://github.com/trpc/trpc/issues/3340
## ✅ Checklist

Screen Shot 2022-12-06 at 3 37 13 PM

Screen Shot 2022-12-06 at 3 38 11 PM

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by juliusmarminge — COMMENTED** [review]
Seems fine to me on Safari and Chrome, however Firefox isn't the best still - quite a lot of shifting:

https://user-images.githubusercontent.com/51714798/205978858-b5fe820b-26c6-45bb-82fc-c67ca32c68f8.mp4

**Comment by neo773** [comment]
> Seems fine to me on Safari and Chrome, however Firefox isn't the best still - quite a lot of shifting:
> 
> https://share.cleanshot.com/KsMarn

Pushed a new commit, it's fixed on FireFox now.

**Comment by juliusmarminge** [comment]
>  it's fixed on FireFox now.

Still shifting for me https://share.cleanshot.com/W8Zx8M

**Comment by neo773** [comment]
> > it's fixed on FireFox now.
> 
> Still shifting for me https://share.cleanshot.com/W8Zx8M

I'm unable to reproduce this on my end running latest Firefox

https://user-images.githubusercontent.com/62795688/206006802-9c5042d0-8d72-45b4-8d23-51acba7ecacf.mp4

**Comment by juliusmarminge** [comment]
> > > it's fixed on FireFox now.
> 
> > 
> 
> > Still shifting for me https://share.cleanshot.com/W8Zx8M
> 
> 
> 
> I'm unable to reproduce this on my end running latest Firefox
> 
> 
> 
> https://user-images.githubusercontent.com/62795688/206006802-9c5042d0-8d72-45b4-8d23-51acba7ecacf.mp4
> 

Bronsers are hard and i hate it...

**Comment by juliusmarminge** [comment]
https://user-images.githubusercontent.com/51714798/206309527-f247ef0d-0d19-4283-8d99-87a22deb0469.mp4

This is annoying... might be Retina display being weird with resolution?

**Comment by KATT** [comment]
We could just remove one of the items from the top too right instead of doing all of this stuff? Or rephrase them

**Comment by KATT** [comment]
Superseded by #3371

**Pull request closed without merging**
