### PR TITLE
svelte wip

### PR DESCRIPTION
**Pull request by KATT**

### CODE REVIEW

**Comment by benbender** [comment]
Hey @KATT,

as said before, I think `TRPC` + `SvelteKit` could be a match made in heaven. What I'm thinking about is (very roughly) the following:

- @trpc/server adapted to `sveltekit`'s concept of endpoints.
- @trpc/svelte with an "adapter" into `sveltekit`'s load-interface for typesafe data-loading & ssr
- Client-side caching with a svelte-adaption of react-query
- An action to tap into the handling of forms to abstract the correlation between forms and trpc-mutations. (see https://github.com/noahsalvi/svelte-use-form or https://github.com/pablo-abc/felte)

I don't think its to hard to pull this off, besides some questionmarks around the limited exposure of the request/response-objects by sveltekit. If this would be tightly integrated, one could get large chunks of the CRUD-workflow in a validated, typesafe, dry kind of way. Without loosing much flexibility in terms of styling and such (as much of the other solutions require).

**Comment by KATT** [comment]
All in all, I've put this on pause for now. 

Personally, I love the idea of Svelte but I will always opt-in for a homogeneous tech stack to avoid cognitive context switching, therebefore I will always opt for React in my tRPC-based project as it allows the team to move to React Native gracefully.

Anyone in the community is free to pick this up and I'll happily help by both guiding around the codebase and to jump on calls to assist.

---

To respond to @benbender:

> * @trpc/server adapted to `sveltekit`'s concept of endpoints on the server.

This is largely done

> * @trpc/svelte with an "adapter" into `sveltekit`'s load-interface for typesafe data-loading & ssr on the client

Think this would be easy

> * Client-side caching with a svelte-adaption of react-query (see https://github.com/SvelteStack/svelte-query, but I would like to see some kind of an adapter like https://github.com/DamianOsipiuk/vue-query instead of a half-maintained fork)

Not used SvelteKit enough to assess this.

> * An action to tap into the handling of forms to abstract the correlation between forms and trpc-mutations. (see https://github.com/noahsalvi/svelte-use-form or https://github.com/pablo-abc/felte)

Unsure if this should be in scope, but would be nice.

**Comment by benbender** [comment]
@KATT Sad to here you are abandoning the idea for now, but thanks for the pointers. I'm also on a project atm which doesn't use svelte and won't have time to work on this any time soon. Maybe someone else picks up the stick. As always: thanks for your work! :)

**Comment by KATT** [comment]
> @KATT Sad to here you are abandoning the idea for now, but thanks for the pointers. I'm also on a project atm which doesn't use svelte and won't have time to work on this any time soon. Maybe someone else picks up the stick. As always: thanks for your work! :)

Yeah, it's enough for me to maintain the React-ecosystem of tRPC but will probably pick this up in the future

**Comment by KATT** [comment]
BTW @benbender, join the trpc discord - trpc.io/discord 😄

**Comment by benbender** [comment]
> Yeah, it's enough for me to maintain the React-ecosystem of tRPC but will probably pick this up in the future

No hard feelings in any way. Would just love to see a great integration. I meant what I said in my last sentence: Your work is appreciated and limiting the own scope is much better then doing too much half-ways!

> BTW @benbender, join the trpc discord - trpc.io/discord 😄

I will as soon as I'm getting the chance to work with trpc again (preferably with svelte :))

**Pull request closed without merging**
