### PR TITLE
Added Example with tRPC Shield(Express Server + Prisma)

### PR DESCRIPTION
**Pull request by omar-dulaimi**

### CODE REVIEW

**Comment by sachinraja** [comment]
I think this example should be in the trpc-shield repo so it can easily stay up to date if anything changes. We could still link to it in the examples page.

**Comment by KATT** [comment]
> I think this example should be in the trpc-shield repo so it can easily stay up to date if anything changes. We could still link to it in the examples page.

I haven't made up my mind on this yet -- it's quite cool how next.js for instance [has a massive examples folder](https://github.com/vercel/next.js/tree/canary/examples).

**Comment by KATT** [comment]
tRPC-shield **definitely** should be added to https://trpc.io/docs/awesome-trpc though

**Comment by KATT** [comment]
> @KATT @sachinraja So other than adding trpc shield to the awesome list, should I close this PR?

Let's do this for now!:

- [ ] Change it to have a readme with a link to your repo like the [kitchen sink](https://github.com/trpc/trpc/tree/main/examples/kitchen-sink)
- [ ] Add it to awesome tRPC


Thanks again for your contributions! It's really fun to see :)

**Pull request merged**
