### PR TITLE
fix: error with cause

### PR DESCRIPTION
**Pull request by skarab42**
Related to #1773

### CODE REVIEW

**Comment by skarab42** [comment]
@KATT I think it's OK to upgrade to 4.6.3

**Comment by skarab42** [comment]
I wonder if this is a breaking change for people who publish plugins outside the tRPC eco system?

**Comment by sachinraja** [comment]
This is fixed on next due to it being a slight breaking change (see #1727)

**Comment by KATT** [comment]
Thanks for this @skarab42, closing as it's fixed on the `next`-branch

**Pull request closed without merging**
