### PR TITLE
docs: update endorsements

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes #

## 🎯 Changes

The Twitter testimonials were mostly from 2021. Added some new ones including tweets from well known people in the web dev community.

Links to the new tweets:

https://twitter.com/mattpocockuk/status/1537761528962764802
https://twitter.com/TkDodo/status/1573391189373751297
https://twitter.com/t3dotgg/status/1571922456239284224
https://twitter.com/ralex1993/status/1556619478556876802
https://twitter.com/mgechev/status/1549140656752234496
https://twitter.com/tannerlinsley/status/1507753424187650048
https://twitter.com/colinhacks/status/1629950516242313216

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by Nick-Lucas — APPROVED** [review]
Cool

**Review by juliusmarminge — APPROVED** [review]
oh sheesh you went and did all this manually (escape characters etc etc...

**Comment by c-ehrlich** [comment]
> oh sheesh you went and did all this manually (escape characters etc etc...

i copy pasted the embed codes from twitter and fixed the html bits that jsx doesnt like. is there another way?

**Comment by juliusmarminge** [comment]
> > oh sheesh you went and did all this manually (escape characters etc etc...
> 
> 
> 
> i copy pasted the embed codes from twitter and fixed the html bits that jsx doesnt like. is there another way?

No i just mean we had a script before when the twitter api was free :)

**Pull request merged**
