### PR TITLE
fix: next-app-dir build fails

### LINKED ISSUE #4396: help wanted: app dir example build fails b/c of mysterious reasons
### Context

- https://github.com/trpc/trpc/tree/main/examples/.experimental/next-app-dir fails to build, but **only** within our monorepo
- https://github.com/trpc/examples-next-app-dir works fine
- Demo: #4397
- Has something to do with a combination of using server actions + pnpm symlinks(?). Possibly b/c of an underlying Next.js/React issue
- More minimal repro: #4393

Eligible for the bounty if you fix it or can reproduce it in a standalone repo to send to the Next.js team.

### Error:

> ```
> > next build
> 
> - warn You have enabled experimental feature (serverActions) in next.config.js.
> - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> 
> Failed to compile.
> 
> ../../../packages/client/dist/index.mjs + 9 modules
> Cannot get final name for export 'observable' of ../../../packages/server/dist/observable/index.mjs
> 
> 
> > Build failed because of webpack errors
> - info Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.
> ```

<sub>[TRP-33](https://linear.app/trpc/issue/TRP-33/help-wanted-app-dir-example-build-fails-bc-of-mysterious-reasons)</sub>

### PR DESCRIPTION
**Pull request by nghiepdev**
`Cannot get final name for export 'observable' of ....`

Fixes #4396

## 🎯 Changes
Revert the custom optimization configuration in webpack. Next.js provides support for [serverComponentsExternalPackages](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages) to address this issue./
For me, `config.optimization.concatenateModules = false` causes some other strange errors.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
CI fails with the same error now

**Comment by nghiepdev** [comment]
> CI fails with the same error now

I think because `@trpc/server` is linked to the internal workspace `@trpc/server` using the path `link:./packages/server`.
https://github.com/trpc/trpc/blob/29c3d666a1984d870c8fb826b1fb619087145f93/pnpm-lock.yaml#L9

**Comment by juliusmarminge** [comment]
> > CI fails with the same error now
> 
> I think because `@trpc/server` is linked to the internal workspace `@trpc/server` using the path `link:./packages/server`.
> 
> https://github.com/trpc/trpc/blob/29c3d666a1984d870c8fb826b1fb619087145f93/pnpm-lock.yaml#L9

Same error without it (using the `prefer-workspace-packages` instead):

CleanShot 2023-06-30 at 14 44 25@2x

CleanShot 2023-06-30 at 14 44 44@2x

**Comment by nghiepdev** [comment]
@juliusmarminge 
I see that `@trpc/server` is still using workspace package
image

The best approach would be to try with https://github.com/trpc/examples-next-app-dir

**Comment by juliusmarminge** [comment]
> @juliusmarminge 
> 
> I see that `@trpc/server` is still using workspace package
> 
> image
> 
> 
> 
> The best approach would be to try with https://github.com/trpc/examples-next-app-dir

Well... we need it working in CI so we need to use the local packages. Afaik it works out of the box (no config needed) when you're not in the monorepo, at least it did before.

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
