### PR TITLE
Update to Docusaurus v3

### LINKED ISSUE #5217: docs/www: update docusaurus and typedoc
### Area of Improvement

Docusaurus has released v3: https://docusaurus.io/blog/releases/3.0. Would be nice to update.

As part of this, I think we need to update typedoc, but not sure

### Link to related docs

_No response_

### Additional information

- I had a stab at this in #5181 but it required more time and effort than I had that day.
- See https://github.com/trpc/trpc/tree/main/www

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5217">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5217/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by roy9495**
Closes #5217 

## 🎯 Changes

Updated to Docusaurus v3
Changed mdx fixes accordingly

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by roy9495** [comment]
I tried to do that many times but it is showing me this error 
~~~
pnpm install
Scope: all 36 workspace projects
 WARN  8 deprecated subdependencies found: @npmcli/move-file@2.0.1, loupe@2.3.6, querystring@0.2.0, querystring@0.2.1, rollup-plugin-inject@3.0.2, sourcemap-codec@1.4.8, stable@0.1.8, superagent@7.1.6
..                                       |   +4   -4 +-
..                                       | Progress: resolved 2837, reused 2690, downloaded 4, added 4, done
../node_modules/.pnpm/@registry.npmjs.com+prisma+-@prisma-4.14.1.tgz+id=%25252525252525252540exampleslegacy-next-starter/node_modules/prisma: Running preinstall script...
../node_modules/.pnpm/@registry.npmjs.com+prisma+-@prisma-4.14.1.tgz+id=%25252525252525252540examplestrpc-next-prisma-todomvc/node_modules/prisma: Running preinstall script...
../node_modules/.pnpm/@registry.npmjs.com+prisma+-@prisma-4.14.1.tgz+id=%25252525252525252540exampleslegacy-next-starter/node_modules/prisma: Runnin../node_modules/.pnpm/@registry.npmjs.com+prisma+-@prisma-4.14.1.tgz+id=%25252525252525252540examplestrpc-next-prisma-todomvc/node_modules/prisma: Running preinstall script, done in 154msom+prisma+-@prisma-4.14.1.tgz+id=%25252525252525252540examplestrpc-next-prisma-starter/node_modules/prisma: R
../node_modules/.pnpm/@registry.npmjs.com+prisma+-@prisma-4.14.1.tgz+id=%25252525252525252540examplesnext-websockets-starter/node_modules/prisma: Running preinstall script, done in 163mss
.. postinstall$ pnpm codegen
│ > root@ codegen /workspaces/trpc
│ > run-p codegen:*
│ > root@ codegen:override-prisma /workspaces/trpc
│ > tsx scripts/addPrismaOverrides.ts
│ > root@ codegen:entrypoints /workspaces/trpc
│ > turbo codegen-entrypoints
│ > root@ codegen:tests /workspaces/trpc
│ > turbo codegen-tests
│  ERROR  run failed: Package tasks (<package>#<task>) are not allowed in single-package repositories: found @examples/minimal-react#build
│  ELIFECYCLE  Command failed with exit code 1.
│  ERROR  run failed: Package tasks (<package>#<task>) are not allowed in single-package repositories: found @examples/minimal-react#build
│  ELIFECYCLE  Command failed with exit code 1.
│  ELIFECYCLE  Command failed.
│ ERROR: "codegen:tests" exited with 1.
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 4.2s at /workspaces/trpc
 ELIFECYCLE  Command failed with exit code 1.
~~~

**Comment by juliusmarminge** [comment]
Here's the errors I'm getting:

<iframe src="https://app.warp.dev/block/embed/iFOoh2Ytu43zTYxlauwjUg" title="embedded warp block" style="width: 1872px; height: 75523px; border:0; overflow:hidden;" allow="clipboard-read; clipboard-write"></iframe>

**Comment by juliusmarminge** [comment]
What's weird is that we don't have these snippets anymore, so I'm not sure where it's referencing those from???

CleanShot 2024-01-26 at 10 13 24

**Comment by juliusmarminge** [comment]
Aight @roy9495, I fixed all the build issues and Shiki problems.

Now it's just the MDX v3 migration left. You up for it?

**Comment by roy9495** [comment]
> Aight @roy9495, I fixed all the build issues and Shiki problems.
> 
> Now it's just the MDX v3 migration left (Fixing all of these errors https://app.warp.dev/block/N0JozPvakENsLbpM8PMzYl). You up for it?

Yes, sure

**Comment by roy9495** [comment]
I got rid of all the previous errors but this new error is showing up.

Capturetrprc

 Can anybody help?

**Comment by juliusmarminge** [comment]
> I got rid of all the previous errors but this new error is showing up.
> 
> Capturetrprc
> 
> Can anybody help?

I am still getting the same errors - did you forget to push?

https://app.warp.dev/block/HQVxSbYEsqetIZiydBMA4S

**Comment by roy9495** [comment]
> > I got rid of all the previous errors but this new error is showing up.
> > Capturetrprc
> > Can anybody help?
> 
> I am still getting the same errors - did you forget to push?
> 
> https://app.warp.dev/block/HQVxSbYEsqetIZiydBMA4S

sorry

**Comment by juliusmarminge** [comment]
Got it to build by disabling typedoc and `prism-react-renderer`. 

typedoc might need a dependency bump to work with docusaurus 3?

prism idk why that didn't work, it complained that it was undefiend...

**Comment by parthmanhas** [comment]
Hi @juliusmarminge, I created a new pull request [here](https://github.com/trpc/trpc/pull/5422) where I was able to build locally with typedoc files. I wanted to commit to this branch but did not have sufficient permissions.

**Comment by roy9495** [comment]
@parthmanhas Hey there! It looks like the build failed with the changes you made.

**Comment by roy9495** [comment]
Is this the dependency bump https://github.com/tgreyuk/typedoc-plugin-markdown/blob/next/packages/docusaurus-plugin-typedoc/CHANGELOG.md#100-next18-2023-10-21?

**Comment by KATT** [comment]
Superseded by #5719

**Pull request closed without merging**
