### PR TITLE
feat: lower compile targets for browser-facing packages

### LINKED ISSUE #3393: feat: lower compile targets for browser-facing packages
### Describe the feature you'd like to request

Currently, we don't do any transpilation outside of what's in tsconfig, which leads to limited browser support, even in compiled output for i.e. Next.js apps. If you search your compiled `_app.js`-bundle, it has a lot of optional chaining which all browsers doesn't support.

### Describe the solution you'd like to see

Either use babel or update tsconfig for browser-facing packages (`@trpc/react-query`, `@trpc/client`) to support older browsers.

The minimum requirement for tRPC is for the browser to support `Proxy`, so we should compile just after that.

### Describe alternate solutions

Unsure, maybe a guide how to transpile code for older browsers?

### Additional information

- In v9, we had babel: https://github.com/trpc/trpc/blob/v9.x/packages/client/package.json#L34
- Unlikely to add extra payload as the likelihood of another dep needing babel is also high.
- TanStack babel config: https://github.com/TanStack/query/blob/main/babel.config.js

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-38](https://linear.app/trpc/issue/TRP-38/feat-lower-compile-targets-for-browser-facing-packages)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3393">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3393/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by gooff327**
Closes #3393

## 🎯 Changes

Lower compile target - from `es2020` to `es5`
related [issue](https://github.com/trpc/trpc/issues/3393)
scope: `@trpc/client`,`@trpc/react-query`

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
Can't understand why at first glance why but it breaks a lot of tests

**Comment by gooff327** [comment]
@KATT All required steps in the workflow have passed now.

**Comment by QuiiBz** [comment]
As a side note: all ES2020 features are supported between 92% and 95% of all users. Only IE doesn't support any of them:

Screenshot 2023-03-30 at 21 39 47

**Comment by juliusmarminge** [comment]
What are the consequences for bundle size with this?

@tanstack/react-query is bumping their required browser version to reduce the bundle size. Is there a point for trpc to reduce if it wont be supported in react-query?

**Comment by gooff327** [comment]
> What are the consequences for bundle size with this?
> 
> @tanstack/react-query is bumping their required browser version to reduce the bundle size. Is there a point for trpc to reduce if it wont be supported in react-query?

If more compatible codes are packaged, the overall size will definitely increase, but it can be ignored after gzip.

**Pull request closed without merging**
