### PR TITLE
feat: add video to awesome-trpc

### PR DESCRIPTION
**Pull request by tomanagle**
- Adds `Build a Blog With tRPC, TypeScript, Next.js, Prisma & Zod` to the awesome-trpc page

### CODE REVIEW

**Review by ixahmedxi — APPROVED** [review]

**Comment by KATT** [comment]
@all-contributors add @tomangle for video, talks, tutorial

**Comment by KATT** [comment]
@all-contributors add @TheoBr for video, talks, tutorial

**Comment by KATT** [comment]
@all-contributors add @tomanagle for video, talk, tutorial

**Comment by KATT** [comment]
@all-contributors add @tomanagle for video, talk, tutorial

**Comment by KATT** [comment]
sorry for the spam 🗡️

**Pull request merged**
