### PR TITLE
Added Yandex Cloud support (#4807)

### LINKED ISSUE #4807: feat: Yandex Cloud Serverless support
### Describe the feature you'd like to request

Would be nice if this supports Yandex Cloud Serverless functions (almost compatible with Lambda)

### Describe the solution you'd like to see

see PR

### Describe alternate solutions

I was thinking of creating separate adapter, but the difference is too small

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4807">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4807/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by dmatora**
Closes #4807 

## 🎯 Changes

Added Yandex Cloud Serverless Functions and API Gateway support

## ✅ Checklist

- [x ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — CHANGES_REQUESTED** [review]
Please add some tests that goes down these code paths


https://github.com/trpc/trpc/blob/main/packages/tests/server/adapters/lambda.test.tsx

**Comment by KATT** [comment]
Actually, I just realised this isn't a lambda. It needs it's own adapter, I'll respond further on #4807

**Comment by dmatora** [comment]
What do you mean with it's not lambda?

**Comment by KATT** [comment]
I mean it isn't an AWS lambda which this adapter is built for

**Pull request closed without merging**
