### PR TITLE
chore: use simple-git-hooks and lint-staged to lint commit files

### PR DESCRIPTION
**Pull request by sun0day**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

Just a development experience optimization. Use simple-git-hooks and lint-staged to lint commit files

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/next/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by sun0day** [comment]
Why treat `eslint` `prettier` `rollup` etc as dependencies, not devDependencies? It is a bit weird.

**Comment by juliusmarminge** [comment]
> Why treat `eslint` `prettier` `rollup` etc as dependencies, not devDependencies? It is a bit weird.

Because it's a private package and not published or built so they are the same: 
CleanShot 2022-11-04 at 16 00 37

**Comment by sun0day** [comment]
> > Why treat `eslint` `prettier` `rollup` etc as dependencies, not devDependencies? It is a bit weird.
> 
> Because it's a private package and not published or built so they are the same: CleanShot 2022-11-04 at 16 00 37

Got it!

**Comment by sachinraja** [comment]
Thanks for the PR but we're not going to add pre-commit hooks. We instead encourage contributors to properly setup their editors. For VSCode, [we recommend](https://github.com/trpc/trpc/blob/next/.vscode/extensions.json) the prettier and eslint extensions.

**Pull request closed without merging**
