### PR TITLE
feat(react): allow conditional ssr based on context

### LINKED ISSUE #4996: feat: Allow making `ssr` conditional on the request
### Describe the feature you'd like to request

Currently, `ssr` is set at at compile time/statically, as a single boolean field on `createTRPCNext`

```ts
export const api = createTRPCNext<AppRouter>({
  config(opts) {
    const { ctx } = opts;

    const link = httpLink({
      url: `${getBaseUrl()}/api/trpc`,
    });

    return {
      links: [
        loggerLink({
          enabled: (opts) =>
            process.env.NODE_ENV === "development" || (opts.direction === "down" && opts.result instanceof Error),
        }),
        link,
      ],
      queryClient,
    };
  },
  ssr: false,
});
```

However, sometimes you want ssr to be conditional - for instance, for all google bot requests, we'd like to SSR the page so that the initial html contains all our meta tags

### Describe the solution you'd like to see

Allow making `ssr` a back, just like config, where you can pull the `NextPageContext`

```ts
export const api = createTRPCNext<AppRouter>({
  config(opts) {
    const { ctx } = opts;

    const link = httpLink({
      url: `${getBaseUrl()}/api/trpc`,
    });

    return {
      links: [
        loggerLink({
          enabled: (opts) =>
            process.env.NODE_ENV === "development" || (opts.direction === "down" && opts.result instanceof Error),
        }),
        link,
      ],
      queryClient,
    };
  },
  ssr(opts){
    const { ctx } = opts;
    const { req } = ctx;
    return req?.headers?.['user-agent']?.includes('googlebot')
  }
});
```

### Describe alternate solutions

We need access to the request. So another solution might be to allow a hook in `utils` to set it at react runtime on the server.

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4996">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4996/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by jonluca**
Closes #4996 

## 🎯 Changes

Allows `ssr` to be passed as a callback instead of a strict boolean, and to make the SSR pass conditional on the context

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — CHANGES_REQUESTED** [review]
Add tests 🙏

**Comment by jonluca** [comment]
@KATT is there already a place with tests for `createTRPCNext`? I'm not sure how to set up some nextjs specific tests in the testing setup of this repo.

**Comment by KATT** [comment]
> @KATT is there already a place with tests for `createTRPCNext`? I'm not sure how to set up some nextjs specific tests in the testing setup of this repo.

Sorry for the slow response

https://github.com/trpc/trpc/blob/main/packages/tests/server/react/withTRPC.test.tsx

You can probably add here

**Comment by jonluca** [comment]
@KATT done! thanks!

**Review by KATT — APPROVED** [review]

**Pull request merged**
