### PR TITLE
fix(client): createInnerProxy exclude apply bind and call

### PR DESCRIPTION
**Pull request by bluecco**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

bug fix: check `.call` and `apply` method for `createInnerProxy`

followup of: https://github.com/trpc/trpc/pull/3973

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
What does this fix? None of our stuff relies on `.bind()` afaik

**Comment by bluecco** [comment]
hi @KATT, this prevent `trpc` to break when using polyfill for async or `regenerator-runtime` package
in that case, `.call` is used to invoke functions.

never had `.bind` too, is to cover all the cases possible (was also mentioned here [https://github.com/trpc/trpc/pull/3973#issuecomment-1468611461](#3973) but never answered)

**Comment by KATT** [comment]
Ok, I'm not sure this is working properly though, please add tests 🙏

**Comment by bluecco** [comment]
@KATT added tests and updated the logic in `createProxy.ts`
image

`.call` needs to send an array as args (otherwise it would fail in `createTRPCClient.ts`)

also removed the check for `.bind()`, as you said nothing relies on that (checked codebase and did multiple tests, ok to remove it)

**Review by KATT — APPROVED** [review]

**Comment by KATT** [comment]
If codecov has gone down, does the test actually test the new thing? 👀

**Comment by KATT** [comment]
cc @bluecco I think I fixed codecov reporting. I can't update the PR as you haven't allowed edits from contributors

**Pull request closed without merging**
