### PR TITLE
feat: React Query Utils outside of React Context

### LINKED ISSUE #4974: feat: Use query helpers outside of Context
### Describe the feature you'd like to request

Like `useUtils` but can be accessed from outside of React context. Basically [this context value](https://github.com/trpc/trpc/blob/a98dc662d6ade1bcfdae09a274d508c9dc347235/packages/react-query/src/shared/hooks/createHooksInternal.tsx#L79) to be made available from a function that is called with a `client` and `queryClient`.

This would help us do prefetching of data at the router level, where context is not accessible. Having the full set of query utils would also be useful at this level for actions where we might want to perform cache invalidation after a mutation.

It's a [recommended pattern in the TanStack Query docs](https://tanstack.com/query/latest/docs/react/guides/prefetching#router-integration) for implementing prefetching and enabling fetch-as-you-render patterns with the now stable Suspense support.

### Describe the solution you'd like to see

A function that creates the same object as `useUtils`. It would take in the `client` and `queryClient` as parameters.

```ts
import { createQueryUtils } from '@trpc/react-query';

const utils = createQueryUtils({ client, queryClient });
await utils.post.all.prefetch();
```

Example usage in a React Router loader, a function which executes before React rendering and has no access to Context or hooks.

```tsx
import { createQueryUtils } from '@trpc/react-query';

const routes = [{
  path: ':postId',
  element: <Post />,
  loader: ({ params }) => {
    // Assume we have a way of getting the client instances into here depending on server/client.
    const utils = createQueryUtils({ client, queryClient });
    
    // Don't navigate until main content is ready.
    await utils.post.byId.prefetch(params.postId);

    // Start fetching comments early but don't block navigation.
    void utils.post.comments.prefetch(params.postId);
  },
}];
```

### Describe alternate solutions

`createServerSideHelpers` only works on the server, meaning we could only do this kind of prefetching for the initial SSR load. We can't perform prefetching or implement these same fetching patterns on the client.

It's more useful to have this at the router level so we can have the same prefetching logic working seamlessly on both server and client.

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4974">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4974/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### LINKED ISSUE #5129: feat: Query Client Utility Methods outside React Context
### Describe the feature you'd like to request

In my project I would like to be able to prefetch a query by using the `ensureData()` function in a react-router-loader to pre-populate the query client cache.

### Describe the solution you'd like to see

I would like to see a generic `utils` instead of `useUtils()` so that ensureData may be called outside of the react context but still be typed with tRPC and populate the QueryClient query cache.

### Describe alternate solutions

Currently in my project I'm defining a vanilla trpc client and using getQueryKey to find the key for the query I wish to pre-fetch. 
```ts
const result = await queryClient.ensureQueryData({
    queryKey: getQueryKey(trpc.auth.status),
    queryFn: () => trpcProxyClient.auth.status.query(),
  });
  ```

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5129">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5129/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by sebasptsch**
Closes #5129
Closes #4974 

## 🎯 Changes

Add typed react-query client utility methods for use outside React context.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by sebasptsch** [comment]
@juliusmarminge , for applications that use SSR this is definately true but client side applications such as applications that use prefetching in React Router loaders use this all the time.

[RQ v4 SSR](https://tanstack.com/query/v4/docs/react/guides/ssr#using-nextjs)
[RQ v4 React Router](https://tanstack.com/query/v4/docs/react/examples/react/react-router)

**Comment by sebasptsch** [comment]
Should be good for review. The only failing tasks are unapproved vercel workflow runs.

**Comment by sebasptsch** [comment]
@juliusmarminge would you mind taking another look?

**Comment by KATT** [comment]
I think we'll want to change the target so this is for the `next`-branch to avoid working out the conflicts this will cause

**Comment by sebasptsch** [comment]
> I think we'll want to change the target so this is for the `next`-branch to avoid working out the conflicts this will cause

Ok, I'll migrate the changes there to make it easier for future development. Thanks for the heads up.

**Comment by sebasptsch** [comment]
Re-created for `next` #5155

**Pull request closed without merging**
