### PR TITLE
docs: info on `httpBatchLink` support for API Gateway multi-resource

### LINKED ISSUE #5738: docs: httpBatchLink can only be used with API Gateway + Lambda if using a single resource for the router
### Area of Improvement

Maybe it's worth mentioning this in the docs. 

### Link to related docs

_No response_

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5738">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5738/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by andrestone**
Closes #5738

## 🎯 Changes

Info on `httpBatchLink` support for API Gateway + Lambda.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — APPROVED** [review]
Thanks! Would love to add support for httpBatchLinkStreamLink too in lambda if you're keen on contributing more, happy to show you the ropes if you hop into discord and @ me. I know lambdas has support for streaming. Also working on adding support for SSE which could work for serverless too (even if it might be pricey)

**Comment by KATT** [comment]
hey @andrestone, can you target `next` instead? we're not really working on `main` actively (which is v10)

**Comment by KATT** [comment]
the edit button on the site should've forked `next` afaict

**Comment by andrestone** [comment]
> Thanks! Would love to add support for httpBatchLinkStreamLink too in lambda if you're keen on contributing more, happy to show you the ropes if you hop into discord and @ me. I know lambdas has support for streaming. Also working on adding support for SSE which could work for serverless too (even if it might be pricey)

Thanks for letting me know. I'll try and give it a shot when I find some room. 

Cheers!

**Pull request closed without merging**
