### PR TITLE
feat: require transformers on frontend & backend when present

### LINKED ISSUE #3276: feat: improve DX when setting up transformers
### Describe the feature you'd like to request

A very common pitfall is that we get bug reports that "tRPC is not working" because the user has defined the transformer on only the backend or only the frontend.

### Describe the solution you'd like to see

Leverage the type `DefaultDataTransformer` similarly to how we did on #3261 to force the user to define a frontend transformer if they've defined a backend one.

### Desribe alternate solutions

- Not doing it
- Some dev only warning? We can probably detect this?
- FAQ page (#2740)

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

### PR DESCRIPTION
**Pull request by QuiiBz**
Closes #3276

## 🎯 Changes

Require the same transformer type on frontend and backend:

- When a transformer is set on the backend but not on the frontend, the frontend will throw an error and tell us that `transformer` is required
- When a transformer is set on the frontend but not on the backend, the frontend will throw an error and tell us that `transformer` is not assignable to `You must set a transformer on the backend router` (note: I'm not sure if this is the best way to inform the user about the issue)

https://user-images.githubusercontent.com/43268759/208251565-5997d330-df84-4759-ba2c-17cbf63e47fb.mov

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
Needs a test :)

You can create a regression test or just a file

Use `// @ts-expect-error` to assert it fails

Ideally we'd test React & Next too but I think they all use `CreateTRPCClientBaseOptions`

**Comment by QuiiBz** [comment]
Yeah, still working on it to also throw an error when we provide a transformer on the frontend but not on the backend. Wil add tests after that!

**Comment by KATT** [comment]
> [...] when we provide a transformer on the frontend but not on the backend. Wil add tests after that!

That seems impossible I think, feels like a circular dep 😅

**Comment by QuiiBz** [comment]
> That seems impossible I think, feels like a circular dep 😅

Just found a trick, by throwing the error on the frontend instead of the backend. But not sure if that's really a good way to do it:

https://github.com/trpc/trpc/pull/3289/files#diff-17d6fa12f247458a34d34288610bbd74c9879d55a28b6c972aba8fe69af1528fR27-R29

**Comment by KATT** [comment]
Did this die? :)

**Comment by QuiiBz** [comment]
Sorry, I forgot to fix the last types errors. Will check asap

**Comment by QuiiBz** [comment]
I've just updated the PR description with explanations and a video, it's working pretty well. All the errors are thrown on the frontend since we use the type of the router here.

**Review by KATT — APPROVED** [review]

**Pull request merged**
