### PR TITLE
refactor(examples) use playwright test runner

### LINKED ISSUE #1523: Update example to use Playwright's own test runner
Currently the [next-prisma-starter](https://github.com/trpc/trpc/tree/main/examples/next-prisma-starter) uses jest-playwright. It would be better to use Playwright's own test runner.

For reference, one can look at [`calcom/cal.com`](https://github.com/calcom/cal.com/tree/main/apps/web) for how to setup Playwright's own runner

### PR DESCRIPTION
**Pull request by emilbryggare**
Replaces the jest playwright test runner with the default playwright test runner as requested in #1523.

Notable changes:

- Videos renamed to test-results as the test runner can be configured to save more results than just videos.
- The executable path option is kept and should work but this is stated in the docs: "Note that Playwright only works with the bundled Chromium, Firefox or WebKit, use at your own risk"

---

Closes #1523

### CODE REVIEW

**Comment by emilbryggare** [comment]
The browser executable is not found when running in Github Actions. I will need to dig deeper, there may be some clues over here https://github.com/microsoft/playwright/issues/4033. 

Hopefully, I'll have some time for it tomorrow. 🤞

**Comment by emilbryggare** [comment]
@KATT Tests are running well now, had to manually specify browser executable location. Can you see why the next-prisma-starter deployment failed? I am not able to access the logs.

**Comment by KATT** [comment]
@all-contributors add @emilbryggare for examples, test

**Comment by KATT** [comment]
Sorry, had some really busy week. It does seem like something to do with a missing dep

Screenshot_20220227-113816

**Comment by emilbryggare** [comment]
@KATT Thank you, it is fixed now. It was expect-playwright that was causing trouble since jest was removed. It is not required anymore as the default playwright test runner includes all the matchers.

**Review by KATT — APPROVED** [review]

**Comment by KATT** [comment]
Awesome, thanks 🙏

**Pull request merged**
