### PR TITLE
implement getLayout() in examples/next-prisma-starter

### LINKED ISSUE #1276: Implement `getLayout()` in `examples/next-prisma-starter`
Implement `getLayout()` in `/examples/next-prisma-starter`

https://nextjs.org/docs/basic-features/layouts#with-typescript

### PR DESCRIPTION
**Pull request by sachinraja**
closes #1276

* Extract the base layout from `pages/index.tsx` into a separate component (`components/Layout.tsx`).
* Apply `getLayout` in `pages/_app.tsx` 
* Add the layout to `pages/index.tsx` and `pages/post/[id].tsx`

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
Thanks for this!! 

Reviewing from my phone so bad formatting to be expected


- could you rename Layout to DefaultLayout and use it as a fallback?
- make sure _app uses DefaultLayout as a fqlllvaxk
- use the PageWithLayout type on both of the pages?

**Comment by sachinraja** [comment]
> use the PageWithLayout type on both of the pages

Should I leave this out since `Page.getLayout` can be removed if `DefaultLayout` is the fallback?

**Comment by KATT** [comment]
> > use the PageWithLayout type on both of the pages
> 
> Should I leave this out since `Page.getLayout` can be removed if `DefaultLayout` is the fallback?

It's optional on the type you added so better convention to simply have it on all pages

**Comment by KATT** [comment]
Could you make a branch on origin instead and replace this PR so the tests can run?

**Comment by sachinraja** [comment]
#1289

**Pull request closed without merging**
