### PR TITLE
fix(www): collapsible sidebar and breadcrumb cant go to new page (#3230)

### LINKED ISSUE #3230: feat: fix breadcrumbs / use categories on site
### Describe the feature you'd like to request

Breadcrumbs don't work, you can't click the "collapsible" stuff in the sidebar to get to a page

### Describe the solution you'd like to see

We need to use "categories" in Docusaurus.

https://docusaurus.io/docs/sidebar/items#sidebar-item-category

### Additional information

It's in the `/www` folder

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

### PR DESCRIPTION
**Pull request by sun0day**
Closes #3230

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

this is `www` bug fix.

trpc

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by KATT** [comment]
I feel like the https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/links/overview shouldn't exist, the contents of that should be the start of https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/links

I think Docusaurus does this on their site somehow

**Comment by KATT** [comment]
Same with 

https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/trpc (which you get when you click "tRPC"

The first page should be the Introduction, https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/

**Comment by KATT** [comment]
Also, please setup github sponsors so I can send you some $ :)

**Comment by sun0day** [comment]
> Same with
> 
> https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/trpc (which you get when you click "tRPC"
> 
> The first page should be the Introduction, https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/



> I feel like the https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/links/overview shouldn't exist, the contents of that should be the start of https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/links
> 
> I think Docusaurus does this on their site somehow

However, sidebar items will be highlighted together if they are linked to the same doc. Another tricky way is to remove the child sidebar item，e.g `Overview` item below, and link the parent item to the doc.

image

**Comment by KATT** [comment]
We can do like Docusaurus does and just have the main page being the index page, example:

https://docusaurus.io/docs/docs-introduction





We don't need the "Overview" sub-item

**Comment by sun0day** [comment]
> Also, please setup github sponsors so I can send you some $ :)

I have some problems setting up my GitHub sponsor. Thank you for your generosity and don't bother paying. 

PR for fun. 🆒

**Comment by sun0day** [comment]
> Same with
> 
> https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/trpc (which you get when you click "tRPC"
> 
> The first page should be the Introduction, https://www-git-fix-wwwbreadcrumb-trpc.vercel.app/docs/

Done.

**Review by KATT — APPROVED** [review]
Amazing. thanks

**Pull request merged**
