### PR TITLE
docs: make file/folder names more consistent

### PR DESCRIPTION
**Pull request by ahhshm**

### CODE REVIEW

**Review by KATT — COMMENTED** [review]
Checked really quickly now. Just make sure to have redirects for anything that is changing URL

https://github.com/trpc/trpc/blob/main/www/vercel.json

**Comment by ahhshm** [comment]
Checked!

**Comment by ahhshm** [comment]
Checked

**Review by KATT — DISMISSED** [review]
lgtm

**Comment by KATT** [comment]
just got a conflict now

**Review by KATT — CHANGES_REQUESTED** [review]
Needs conflict resolution @ahhshm 🙏

**Review by KATT — APPROVED** [review]

**Pull request merged**
