### PR TITLE
unversion docs

### LINKED ISSUE #2550: feat: make some pages unaffected by versioning
### Describe the feature you'd like to request

https://docusaurus.io/docs/docs-multi-instance#versioned-and-unversioned-doc

> 
> Sometimes, you want some documents to be versioned, while other documents are more "global", and it feels useless to version them.
> 
> We use this pattern on the Docusaurus website itself:
> 
> - The [/docs/*](https://docusaurus.io/docs) section is versioned
> - The [/community/*](https://docusaurus.io/community/support) section is unversioned

### Describe the solution you'd like to see

Move a bunch of pages that shouldn't be versioned like `sponsors`, `contributing`, etc to be unversioned

### Desribe alternate solutions

Do nothing

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #2550

## 🎯 Changes

(Kind of) inversions some docs. At least we don't have to maintain the content of multiple content, but instead just import it. Don't know if it's any better?

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Updated the Github Sponsor button too
Pre:
CleanShot 2022-08-31 at 00 38 17@2x
CleanShot 2022-08-31 at 00 38 57@2x

After: 
https://www-git-julius-unversion-docs3-trpc.vercel.app/docs/v9/contributing

**Comment by juliusmarminge** [comment]
Also aligning breadcrumbs:
CleanShot 2022-08-31 at 00 44 14@2x

**Review by KATT — COMMENTED** [review]
I love it! 

I'm leaning on us versioning awesome-trpc as we'll be able to have different set of reference examples etc for v9 and v10

**Comment by juliusmarminge** [comment]
> I love it!
> 
> I'm leaning on us versioning awesome-trpc as we'll be able to have different set of reference examples etc for v9 and v10

Alright, should I go over the projects listed and check their versions then?

**Comment by KATT** [comment]
Easy to change later, I'll merge it as-is for now! :D

**Pull request merged**
