### PR TITLE
feat(www): make vid clickable and hoverable

### PR DESCRIPTION
**Pull request by KATT**
@ixahmedxi I want your input on how to make this nice

### CODE REVIEW

**Comment by ixahmedxi** [comment]
@KATT when you mention hoverable, is it that you want the user to be able to play/pause the video or rather just a hover effect that gives the user the perception that it is indeed clickable?

**Comment by KATT** [comment]
> @KATT when you mention hoverable, is it that you want the user to be able to play/pause the video or rather just a hover effect that gives the user the perception that it is indeed clickable?

Just to make it feel more like something clickable

**Comment by ixahmedxi** [comment]
> > @KATT when you mention hoverable, is it that you want the user to be able to play/pause the video or rather just a hover effect that gives the user the perception that it is indeed clickable?
> 
> Just to make it feel more like something clickable

okay got it, will play around with it in the morning 🥰

**Comment by ixahmedxi** [comment]
@KATT let me know what you think of the change I've done to the hover effect

**Review by juliusmarminge — DISMISSED** [review]
Looks great imo

**Pull request merged**
