### PR TITLE
chore(lint): Remove redundant eslint configs from examples

### PR DESCRIPTION
**Pull request by kamilogorek**
Fixes failing CI in https://github.com/trpc/trpc/pull/4043

## 🎯 Changes

There were 3 redundant `.eslintrc` configs in examples that were the same as our main config. All `.eslintrc` configs are inherited from the root directory anyway, so they had effectively no effect (other than duplicating the same settings).

This PR removes those files, and unnecessary `package.json` entries and makes the lock file smaller. All while preserving the same behavior.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
These examples are linked to their own repos and are meant to be starter projects people can clone and work on. Removing the eslint config would make that an extra setup step "cloners" would have to do on their own

**Comment by kamilogorek** [comment]
Uh. We don't provide those for any other example repos though 😔

**Comment by juliusmarminge** [comment]
They are here: 
https://github.com/trpc/examples-next-prisma-starter
https://github.com/trpc/examples-next-prisma-websockets-starter
https://github.com/trpc/examples-next-prisma-todomvc
and as they're meant for fully fledged starters, i think they should have eslint configs preconfigured.

There's also this mirror: https://github.com/trpc/examples-next-minimal-starter
But that's meant to be a minimal starter so no need for custom eslint config there

**Comment by kamilogorek** [comment]
Gotcha. Then there has to be something else that prevents https://github.com/trpc/trpc/pull/4043/ from linting correctly locally 🤔  will close this PR once the mystery is solved

**Comment by juliusmarminge** [comment]
> Gotcha. Then there has to be something else that prevents #4043 from linting correctly locally 🤔 will close this PR once the mystery is solved

seems like the lockfile was out-of-sync. i think i fixed it

**Comment by kamilogorek** [comment]
I tried to purge it and it still failed. Oh JS...

**Pull request closed without merging**
