### PR TITLE
chore: use workspace protocol to reference packages

### PR DESCRIPTION
**Pull request by sachinraja**

### CODE REVIEW

**Comment by bautistaaa** [comment]
dang i didn’t realize we weren’t doing this before

**Comment by QuiiBz** [comment]
There's an issue with manypkg not supporting properly `workspace:*`: https://github.com/Thinkmill/manypkg/issues/147

**Comment by bautistaaa** [comment]
> There's an issue with manypkg not supporting properly `workspace:*`: [Thinkmill/manypkg#147](https://github.com/Thinkmill/manypkg/issues/147)

ah that’s a bummer

**Comment by sachinraja** [comment]
closing in favor of #3925, thanks for pointing that out @QuiiBz

**Pull request closed without merging**
