### PR TITLE
docs: reorganize client docs and write new overview article

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes #

## 🎯 Changes

- [x] reorganized client docs to make the structure easier to understand
- [x] wrote new client overview article
- [x] updated urls to reflect the new structure and add redirects to vercel.json
- [x] more consistent naming

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

Docs nav when on the index page:
CleanShot 2023-06-03 at 20 34 40@2x

Fully expanded "Client Usage" nav:
CleanShot 2023-06-03 at 20 35 46@2x

### CODE REVIEW

**Review by KATT — APPROVED** [review]
Looks very thorough.

One nit-pick I have is that I'd love every "expandable" thing in the sidebar to open a page

E.g. opening Next.js integration in this vid is nice, opening links isn't as nice :)

https://github.com/trpc/trpc/assets/459267/ca6fc6bd-6cf0-44a7-90a7-6dff6cbd9025

**Comment by c-ehrlich** [comment]
> Looks very thorough.
> 
> One nit-pick I have is that I'd love every "expandable" thing in the sidebar to open a page
> 
> E.g. opening Next.js integration in this vid is nice, opening links isn't as nice :)
> CleanShot.2023-06-04.at.22.10.21.mp4

Sure, I can move the intro/overview articles "into" the expandable "folder".

That being said would be awesome to change the behaviour to be similar to https://nextjs.org/docs - on their docs, when you click the arrow to expand a section, it also opens that parent article. Currently I think in tRPC docs it's easy to miss that the sections themselves are articles as well. Will take a look and see whether or not this can be implemented easily (in a separate PR)

**Comment by KATT** [comment]
All good! We can do a follow-up, we can smash this in first, thanks for this! 🙏

**Comment by c-ehrlich** [comment]
> All good! We can do a follow-up, we can smash this in first, thanks for this! 🙏

already done :)

(except for api reference, but that's a new article that needs to be written)

**Review by KATT — APPROVED** [review]

**Pull request merged**
