### PR TITLE
feat: added batch capabilities to procedures

### PR DESCRIPTION
**Pull request by i-Welch**
Note: Currently In progress. Opening this for feedback

## 🎯 Changes

This is a feature. I would like to add the ability to specify a procedure as a "batch" procedure. When a procedure is labeled a "batch" procedure (using the .batch()) function and the procedure builder. instead of getting just one input in the handler you will get an array of inputs. You will also be expected to return an array of the same length as the returned data to all the functions you called from the client. Currently the happy path works well as well as using it in conjunction with Input() and Output(). If there is interest I can clean up the last few things I'd need to handle before this code is ready for a merge.

In order to test this you can create a simple sandbox where you mark a procedure as batch like so:
image

## 💡 Rationale

The Rationale for this change is that with the automatic batch that is done on the client side often times it would be more performant to handle those requests all at once instead of one at a time for because you can batch API calls, database calls, etc. This would provide a very simplistic API so that you can continue to leverage the automatic batching done by TRPC on the client side while also taking advantage of it on the server side to get better performance or enable some other behavior that you may desire. This feature is completely opt in on the part of the user of course and should have no backwards breaking changes.

## ✅ Checklist

✅ I have followed the steps listed in the [Contributing guide (https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.
- [ ] Handle error cases
- [ ] Clean up Procedure builder types

### CODE REVIEW

**Comment by KATT** [comment]
I love the work you've put into this PR, but I think we don't wanna go in this direction. 

I don't understand the motivation why - you can already get the same benefits in tRPC if you use a [dataloader](https://github.com/graphql/dataloader) in your data-layer; in fact, you actually get the benefits of this [**for free** with tRPC + Prisma already](https://www.prisma.io/docs/guides/performance-and-optimization/query-optimization-performance) if you're using `.findUnique()`.

**Comment by KATT** [comment]
cc @i-Welch can you share motivation on why you needed this, please?

**Comment by i-Welch** [comment]
@KATT Yes NP. I was actually just creating an example showing off what I'd generally consider one of the stronger use cases. If you look into the /examples folder I created a new example called batch-example. It has a server and a client piece, as well as a ReadMe.md at the top level where I outline my thoughts on the different examples shown in the project. I hope that illustrates the specific use cases in which I think this would be useful.

Just to reiterate something I put at the end of that ReadMe.md thanks for taking the time to review and provide this tech to the community, and if the examples aren't convincing (and I'm under no illusion that I'm incredibly convincing or infallible here) then I'm completely satisfied with the answer either way it goes. Thanks again for taking the time here and if this doesn't seem like its providing much value just let me know and I'll close out the PR.

~ cheers

**Comment by KATT** [comment]
Could you elaborate what problem it solves for you and the application you're working on & why the current batching isn't sufficient in combination with a dataloder?

**Comment by i-Welch** [comment]
Certainly, Take this example of a request diagram on a user interaction
image

You can see here how even though we are batching the requests to TRPC we are handling them sequentially to the 3rd party API. Generally automated data layer batching isn't something I've ever seen over HTTP (some nuance here for certain types of GET requests) and even seldom seen on client libraries which use HTTP as the backing to interact with 3rd party services.

Here is a possible solution to this.
image

This is a valid solution, but in my experience these solutions are often very bug laden and brittle, as well as generally being annoying for developers ergonomically.

Here is another possible solution that is only in user space.
image

I'd say while I think this is easier than the backend equivalent. It does raise its own issues with bugs and dev ergonomics. It also requires the addition of / or modification of the procedure into a batch procedure in many cases via changing input type to an array and then updating logic as needed.

Here is the diagram enabled by the batch changing I'm proposing.
image

I think this is IMO the cleanest solution possible as it removes the pitfalls of the hand rolled batching logic from both the frontend and the backend (in favor of reusing TRPCs on the front-end) but otherwise follows the same benefits gotten from the above example (where the handler can decide how to batch requests and parse responses based on fine-grained user logic). Another benefit here is that is an optimization that is very easy to opt-in to later in a projects lifecycle when optimizations becomes necessary without large or drastic changes to the front-end code.

All in all this is just an optimization though, and not an existential one for any use case as their are user land alternatives possible.

**Comment by i-Welch** [comment]
Thanks for taking a look though! been a pleasure working with you!

**Comment by KATT** [comment]
Thanks for the detailed description! 

For now, we won't add this, but let us know if you have a real need for this in the future. I've made a reference in #4073 on how to add dataloaders in tRPC.

**Pull request closed without merging**
