### PR TITLE
Update pnpm to latest version

### LINKED ISSUE #5340: feat: Use latest version of pnpm
### Describe the feature you'd like to request

I set up `pnpm` by executing the `asdf install` command, utilizing the `.tool-versions` file to install the project's required dependencies. Upon running `pnpm install`, a prompt advised me to update `pnpm`.

### Describe the solution you'd like to see

Update the version of pnpm in `.tool-versions` file
```
nodejs 20.10.0
pnpm 8.14.1
```

### Describe alternate solutions

**Alternative:** Install pnpm globally
But installing pnpm globally can lead to inconsistencies, as not every developer may be using the same version of pnpm.

### Additional information

image

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5340">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5340/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by ThomasCode92**
Closes #5340

## 🎯 Changes

The following commands were used to update the pnpm version for asdf.
```console
asdf install pnpm latest
asdf local pnpm latest
```

To use this new version; just run `asdf install` in your terminal.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by juliusmarminge — CHANGES_REQUESTED** [review]
Please update package.json#packageManager too for corepack users

**Comment by ThomasCode92** [comment]
Updated the version in `package.json` as well

**Review by juliusmarminge — APPROVED** [review]

**Comment by ThomasCode92** [comment]
@juliusmarminge how did you change the `pnpm-lock.yaml `file?

**Comment by juliusmarminge** [comment]
> @juliusmarminge how did you change the `pnpm-lock.yaml `file?

Ran `pnpm install`

**Pull request merged**
