### PR TITLE
Omit jsonrpc key from client-side websocket messages

### LINKED ISSUE #1778: Simplify tRPC Request/Response/Message Interfaces
Originally posted by @KATT 

> See @jlalmes' PR https://github.com/trpc/trpc/pull/1759
> 
> Potential things. Not definitive, just ideas.
> 
> 
> ## Remove  unused fields
> 
> Before:
> 
> ```js
> [
>   {
>     "id": null,
>     "result": {
>       "type": "data",
>       "data": {
>         "id": "1",
>         "title": "Hello tRPC",
>         "body": "..."
>         // ...
>       }
>     }
>   },
> ]
> ```
> 
> After:
> 
> ```js
> [
>   {
>     "result": {
>       "data": {
>         "id": "1",
>         "title": "Hello tRPC",
>         "body": "..."
>         // ...
>       }
>     }
>   },
> ]
> ```
> 
> ## Changed response to a mapped object
> 
> Potential ease of allowing for streaming... maybe we could start sending response as procedures are finalised and not wait for _all of them_ to be finalized before returning... but it also breaks HTTP-codes so not sure.
> 
> Probably not a good idea, just a thought
> 
> ```js
> {
>   // 0 means index 0 of the batch
>   "0": { 
>     "id": null,
>     "result": {
>       "type": "data",
>       "data": {
>         "id": "1",
>         "title": "Hello tRPC",
>         "body": "..."
>         // ...
>       }
>     }
>   },
> ]
> ```
> 
> ## Remove JSONRPC 
> 
> Remove JSNORPC stuff on the request/response for internal requests...
> 
>

### PR DESCRIPTION
**Pull request by jlalmes**
## Omit 'jsonrpc' key from client-side websocket messages.

This PR removes `{ ..., "jsonrpc": "2.0", ... }` from websocket messages made by the `TRPCClient` in the `wsLink`. This is the only payload in the entire tRPC library that where the `jsonrpc` key is not already omitted. It serves no purpose on the server-side.

Closes #1778

### CODE REVIEW

**Comment by KATT** [comment]
This *might* be a breaking change and I'm not confident we should deviate from the spec.

Anyway, would love to have a chat with you on things, if you want, please book a sessh to speak on cal.com/alexander

**Review by KATT — COMMENTED** [review]
It should be there thooooo

https://www.jsonrpc.org/specification#request_object


Not sure. Might wanna remove it indeed, it's not needed for _our_ server/client comm

**Comment by jlalmes** [comment]
On another note: I'm not opposed to adding the `"jsonrpc"` key into HTTP requests and WS messages (server => client), but I think we should definitely strive to achieve a consistent API interface.

**Comment by jlalmes** [comment]
Superseded by https://github.com/trpc/trpc/pull/1780

**Pull request closed without merging**
