### PR TITLE
move transformers to router

### LINKED ISSUE #545: Transformers at server level
https://trpc.io/docs/data-transformers show transformer at the client and in next handlers.  Would it be possible to match the client interface ala

```ts
const appRouter = router<Context>({
  transformer:superjson
})
```
so it working without being tied to Next.js

### PR DESCRIPTION
**Pull request by KATT**
- move data transformers to Router so you don't have to define them on the endpoints
- update docs
- add backwards compatability

closes #545 

---

🙏  review docs: https://www-git-feature-transformers.tmp.trpc.io/docs/data-transformers

### CODE REVIEW

**Review by delaneyj — APPROVED** [review]
Thanks!  I really do want to start providing more PRs but still trying to grok all the new TS features used here.

**Comment by KATT** [comment]
@delaneyj - the best way is probably to look through how the changes, so i'll keep adding you to reviews -- if you want a walkthrough of the internals, book a meeting, you have the link :)

**Comment by simonedelmann** [comment]
@KATT I've just seen this PR. Did you remove the support for combined transformers then? The docs for combined transformers does not include devalue in the server part, so there seems to be something wrong?

**Comment by KATT** [comment]
Ohhh, maybe I fucked up the docs; it should all be backwards compatible though (tests are unchanged). Do you wna make a pr to revert it maybe?

**Pull request merged**
