### PR TITLE
fix types for invalidating routers

### LINKED ISSUE #3122: bug: nested routers allow invalidation with wrong params
### Provide environment information

```
  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 146.83 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.113
    Chrome: 107.0.5304.87
    Firefox Developer Edition: 106.0
    Safari: 15.6.1
  npmPackages:
    typescript: 4.6.2 => 4.6.2 
    @tanstack/react-query: 4.10.3 => 4.10.3 
    @trpc/client: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/next: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/react-query: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/server: 10.0.0-rc.3 => 10.0.0-rc.3 
    next: 12.3.0 => 12.3.0 
    react: 17.0.2 => 17.0.2 
```

### Describe the bug

If you have nested routers, you can use `useContext()` and call `invalidate` on a router with wrong variables, which doesn't work at runtime and should yield a type error (but it doesn't).

### Link to reproduction

https://codesandbox.io/s/festive-star-xjoi30?file=/src/pages/index.tsx

### To reproduce

look at the code for the button that says `this doesn't do anything ❌`

it doesn't do anything at runtime, which is fine, but it should yield a type error when trying to invoke:

```
utils.todos.invalidate({ id: 5 });
```

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### LINKED ISSUE #3123: bug: `setData` input is optional when it should be required
### Provide environment information

```
  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 146.83 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.113
    Chrome: 107.0.5304.87
    Firefox Developer Edition: 106.0
    Safari: 15.6.1
  npmPackages:
    typescript: 4.6.2 => 4.6.2 
    @tanstack/react-query: 4.10.3 => 4.10.3 
    @trpc/client: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/next: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/react-query: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/server: 10.0.0-rc.3 => 10.0.0-rc.3 
    next: 12.3.0 => 12.3.0 
    react: 17.0.2 => 17.0.2 
```

### Describe the bug

calling `setData` doesn't require us to provide `input` even though it's required for the router, so calling it without input doesn't do anything.

### Link to reproduction

https://codesandbox.io/s/sad-galois-hflomu?file=/src/pages/index.tsx

### To reproduce

look at (and click) the button `input is optional for setData 🤨`.

I see two ways how this could play out:

1) calling `setData` on `utils.todos.detail` could try to set data for _all_ matching detail queries. This would be possible via `queryClient.setQueriesData` (plural). It would invoke the updater once for each query.

2) calling `setData` on `utils.todo.detail` should type error, because `input` is required.

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### PR DESCRIPTION
**Pull request by KATT**
- closes #3122
- closes #3123 

## 🎯 Changes

Bug fixes

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/next/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by JonParton** [comment]
I'm personally sad to see it go, however, we also need to remove this from the docs for use context too.

Screenshot_20221106-124411_Chrome

Otherwise I think that does it to remove this!

**Comment by JonParton** [comment]
P. S. Sorry I can't contribute code on mobile! Also the change above is too far out of the current changes for me to suggest changes in the pr review comments!

**Comment by KATT** [comment]
> I'm personally sad to see it go, however, we also need to remove this from the docs for use context too.

I get that. I just don't think the pain outweighs the gain right now since it had some issues. Happy to take it into consideration later on.

Do you actually use this in your app?

**Comment by JonParton** [comment]
> Do you actually use this in your app?

Not right now to be fair! Not a huge loss!

**Comment by KATT** [comment]
> > Do you actually use this in your app?
> 
> Not right now to be fair! Not a huge loss!

If you don't use it, lose it! If you find a big win in adding this to your app later, we'll reconsider adding it! :)

**Comment by JonParton** [comment]
Also the same behaviour can be created with a manual use of the react query query client and a knowledge of how our keys are structured!

I do think a function to get the query key for a router / procedure would be usefull though for use in these kinds of escape hatches! 🤔

**Comment by TkDodo** [comment]
> I do think a function to get the query key for a router / procedure would be usefull though for use in these kinds of escape hatches! 🤔

me too. There are still things uncovered by trpc, like `queryClient.setQueryDefaults` that I would really like to use. It's fine if it doesn't exist directly in trpc, but having to know the (internal) queryKey structure is weird...

**Pull request merged**
