### PR TITLE
Support Set-Cookie header in fetch adapter (3)

### LINKED ISSUE #2312: Cannot set `Set-Cookie` response header
I'm working with implementing authentication using `trpc`. I use the `fetch` adapter. I need to set the `Set-Cookie` response header. However in trying so I discovered that `fetch`'s `Response` objects do not allow setting this header, as per the spec [here](https://fetch.spec.whatwg.org/#forbidden-response-header-name).

> A forbidden response-header name is a [header name](https://fetch.spec.whatwg.org/#header-name) that is a [byte-case-insensitive](https://infra.spec.whatwg.org/#byte-case-insensitive) match for one of:
>
> - `Set-Cookie`
> - `Set-Cookie2`

After some debugging, I was able to come to the conclusion that the problem lies with the `res.headers.set(...)` call on line `52`. The `Headers` object's implementation silently ignores calls to this (and `.append` I think) with the `key` set to one of the above alternative from the spec.

https://github.com/trpc/trpc/blob/2af7a0070f3bc01b81fe6f14f591e77c549520a7/packages/server/src/adapters/fetch/fetchRequestHandler.ts#L42-L59

Fortunately there is a potential solution in my eyes. This would be to extract the header keys and values from `result.headers` before constructing the `Response` object. Passing the new `headers` record into the `headers` option.

```ts
const headers = {};

// collect headers...

const res= new Response(result.body, {
  status: result.status,
  headers,
});
```

I am a little worried this solution might cause problems considering I don't know if this approach would bypass all of `Headers` addition checks. Maybe if this is the case, only extract and inject the "forbidden response-header names" before constructing the `Response` object and continue using the current approach for all rest.

If this behaviour is intentional, or if you require more information please let me know.

Thanks.

### Info

- `trpc`: `10.0.0-alpha.40`

### PR DESCRIPTION
**Pull request by emme1444**
Fix support for Set-Cookie header in fetch adapter.

Closes #2312

@KATT

### CODE REVIEW

**Comment by sachinraja** [comment]
does this work?

**Comment by emme1444** [comment]
@sachinraja from my tests this works. I can't speak for if this is unstable as in a bug or something though. It is a little weird. From what I understand the problem is using the `fetch` interfaces on the server. It seems they were really only meant for the client. Maybe, or something...

The only, annoying, limitation I couldn't get working, is that not more than one cookie can be set per response. This is, I'm guessing, because the `Response` object isn't handling the `Set-Cookie` header differently. Since, it wasn't made for it, I guess? It will just concatenate multiple values with a comma. Which is not what the browser expects for multiple `Set-Cookies`. As I understand it. I'm not an expert.

**Review by KATT — CHANGES_REQUESTED** [review]
Needs tests, see https://github.com/trpc/trpc/blob/next/packages/server/test/interop/adapters/fetch.test.ts

You might want to do the client request raw, without the tRPC client, as the trpc client's query function don't currently expose the returned headers

**Comment by KATT** [comment]
Closing as I haven't heard back on this for over a month, feel free to re-open if this functionality is needed.

**Pull request closed without merging**
