### PR TITLE
feat(client): supply operation to the `httpSubscriptionLink`'s `eventSourceOptions`

### LINKED ISSUE #6148: feat: supply operation to the httpSubscriptionLink eventSourceOptions.
### Describe the feature you'd like to request

I have an authentication scheme that is based on signing the operation with a private key and verifying that with a public key. This is easy to do with httpLink because the function for creating headers is supplied with the operation.

```ts
const client = createTRPCClient<AppRouter>({
  links: [
   httpLink({
     url: apiUrl,
     headers: async (op) => {
        const signature = await signRequest(op.input, op.path, op.type);
        return {
          'x-signature': signature
        };
      }
    })
  ]
});
```

I would like to do the same to authenticate the httpSubscriptionLink with connection options:
```ts
const client = createTRPCClient<AppRouter>({
    links: [
      splitLink({
        condition: op => op.type === 'subscription',
        true: unstable_httpSubscriptionLink({
          url: apiUrl,
          eventSourceOptions: async () => {
            // no operation is supplied so no per request options
            return { headers: {} }
          }
        }),
        false: httpLink({
          url: apiUrl,
          headers: async ({op}) => {
            const signature = await signRequest(op.input, op.path, op.type);
            return {
              'x-signature': signature
            };
          }
        })
      })
    ]
  });
```

### Describe the solution you'd like to see

I would like for the operation that starts the event source to be passed into the function, very much like httpLink.

```ts
const client = createTRPCClient<AppRouter>({
  links: [
    unstable_httpSubscriptionLink({
      url: apiUrl,
      eventSourceOptions: async ({op}) => {
        const signature = await signRequest(op.input, op.path, op.type);
        return {
           headers: {
              'x-signature': signature
            }
         };
      }
    })
  ]
});
```

### Describe alternate solutions

1. I have experimented with doing this as a link but unfortunately that doesn't expose the eventSourceOptions.

### Additional information

I've done a quick implementation and it doesn't break any tests but this is my first contribution so take that with a grain of salt! I tried to port this to wsLink but because that doesn't have a one operation to one connection model, I don't think it makes sense. 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6148">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6148/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by changesbyjames**
Closes #6148

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?
A new feature to supply the operation that initialises an EventSource in httpSubscriptionLink.

## ✅ Checklist

- [X] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — CHANGES_REQUESTED** [review]
I'm fine with the change but please supply a test and update the docs as well

**Comment by changesbyjames** [comment]
Hey @KATT, I'm happy to change the docs but I'm not quite sure where to start on the tests. Could you point to the closest test that would be a good starting point and I'll try my best?

**Comment by KATT** [comment]
some pointers:
- https://github.com/trpc/trpc/blob/next/packages/tests/server/httpSubscriptionLink.test.ts
- https://github.com/trpc/trpc/blob/290a117b356059934a2192731395e521854e3f70/packages/tests/server/httpSubscriptionLink.test.ts#L114-L117

you could e.g. make a new `describe()`-block with a new `const ctx = konn()` that uses this new argument or create a new file for it or edit the existing link-setup in that test

**Comment by KATT** [comment]
`pnpm test-watch httpSub` should be enough to run it when you're deving

**Comment by changesbyjames** [comment]
@KATT Thank you for those pointers! I believe I have resolved everything, please let me know if you'd like me to change anything 🙂

**Pull request merged**
