### PR TITLE
Updating SSR docs

### LINKED ISSUE #1811: Improve docs for SSR on tRPC
From @TheoBr - https://clips.twitch.tv/SleepyVibrantGrasshopperDxCat-ZJjzoC-yQHmSmyDE

- [ ] Add this on the `/examples/next-prisma-starter`: https://github.com/trpc/examples-next-prisma-starter-websockets/blob/main/src/pages/_app.tsx#L75
- [ ] Add docs in https://trpc.io/docs/ssr
- [ ] https://github.com/trpc/examples-next-prisma-starter/blob/db7e2c1469170a660a12a45d7c40829ed4bc9509/src/pages/_app.tsx#L28-L44
- [ ] Make sure you don't use `getServerSideProps` or `getStaticProps` anywhere in the app  (#596)

### PR DESCRIPTION
**Pull request by rhenriquez28**
Closes #1811 

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?
Added client's headers forwarding example
Removed "Caveats" in favor of "FAQ"

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Review by KATT — CHANGES_REQUESTED** [review]
Thanks for your contribution! This is well needed :pray: :pray: 

I've added you as a contributor now, could you please do the following for me? :point_down:

1. Accept the invitation - [link](https://github.com/trpc/trpc/invitations)
1. Push your branch to `origin` / `git@github.com:trpc/trpc.git`
1. Open a new PR from origin instead
1. Close this PR


I really appreciate you spending time helping out with tRPC, feel free to continue to do so. All contributions are welcome, big or small!

**Comment by rhenriquez28** [comment]
Thanks for adding me @KATT ! I already accepted the invitation. However, I'm a little confused on the next steps. Do I open a new branch on `git@github.com:trpc/trpc.git` and then create a new PR? Do I create the new branch based on the `next` branch or the `main` branch?

**Comment by juliusmarminge** [comment]
> Thanks for adding me @KATT ! I already accepted the invitation. However, I'm a little confused on the next steps. Do I open a new branch on `git@github.com:trpc/trpc.git` and then create a new PR? Do I create the new branch based on the `next` branch or the `main` branch?

Hi, you should be able to push your branch directly to upstream. Otherwise, I think the easiest is just to clone `trpc/trpc`, checkout a new branch from next, copy over your changes and push to origin:

```bash
git clone git@github.com:trpc/trpc
git checkout next
git checkout -b henriquez/ssr-docs
# make changes
# commit and push
# make a PR
```

**Comment by rhenriquez28** [comment]
Thank you so much!! Created the PR and closing this one

**Pull request closed without merging**
